<?php

namespace Database\Seeders;

use App\Models\CodigoCiiu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CodigoCiiuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $codigos = [
            ['codigo' => '0111','nombre' =>	'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas '],
            ['codigo' => '0112','nombre' =>	'Cultivo de arroz '],
            ['codigo' => '0113','nombre' =>	'Cultivo de hortalizas, raíces y tubérculos '],
            ['codigo' => '0114','nombre' =>	'Cultivo de tabaco '],
            ['codigo' => '0115','nombre' =>	'Cultivo de plantas textiles '],
            ['codigo' => '0119','nombre' =>	'Otros cultivos transitorios n.c.p.'],
            ['codigo' => '0121','nombre' =>	'Cultivo de frutas tropicales y subtropicales'],
            ['codigo' => '0122','nombre' =>	'Cultivo de plátano y banano'],
            ['codigo' => '0123','nombre' =>	'Cultivo de café'],
            ['codigo' => '0124','nombre' =>	'Cultivo de caña de azúcar'],
            ['codigo' => '0125','nombre' =>	'Cultivo de flor de corte'],
            ['codigo' => '0126','nombre' =>	'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos'],
            ['codigo' => '0127','nombre' =>	'Cultivo de plantas con las que se preparan bebidas'],
            ['codigo' => '0128','nombre' =>	'Cultivo de especias y de plantas aromáticas y medicinales '],
            ['codigo' => '0129','nombre' =>	'Otros cultivos permanentes n.c.p.'],
            ['codigo' => '0130','nombre' =>	'Propagación de plantas (actividades de los viveros, excepto viveros forestales) '],
            ['codigo' => '0141','nombre' =>	'Cría de ganado bovino y bufalino'],
            ['codigo' => '0142','nombre' =>	'Cría de caballos y otros equinos '],
            ['codigo' => '0143','nombre' =>	'Cría de ovejas y cabras '],
            ['codigo' => '0144','nombre' =>	'Cría de ganado porcino'],
            ['codigo' => '0145','nombre' =>	'Cría de aves de corral'],
            ['codigo' => '0149','nombre' =>	'Cría de otros animales n.c.p.'],
            ['codigo' => '0150','nombre' =>	'Explotación mixta (agrícola y pecuaria) '],
            ['codigo' => '0161','nombre' =>	'Actividades de apoyo a la agricultura '],
            ['codigo' => '0162','nombre' =>	'Actividades de apoyo a la ganadería'],
            ['codigo' => '0163','nombre' =>	'Actividades posteriores a la cosecha '],
            ['codigo' => '0164','nombre' =>	'Tratamiento de semillas para propagación '],
            ['codigo' => '0170','nombre' =>	'Caza ordinaria y mediante trampas y actividades de servicios conexas '],
            ['codigo' => '0210','nombre' =>	'Silvicultura y otras actividades forestales'],
            ['codigo' => '0220','nombre' =>	'Extracción de madera '],
            ['codigo' => '0230','nombre' =>	'Recolección de productos forestales diferentes a la madera'],
            ['codigo' => '0240','nombre' =>	'Servicios de apoyo a la silvicultura '],
            ['codigo' => '0311','nombre' =>	'Pesca marítima '],
            ['codigo' => '0312','nombre' =>	'Pesca de agua dulce '],
            ['codigo' => '0321','nombre' =>	'Acuicultura marítima '],
            ['codigo' => '0322','nombre' =>	'Acuicultura de agua dulce'],
            ['codigo' => '0510','nombre' =>	'Extracción de hulla (carbón de piedra)'],
            ['codigo' => '0520','nombre' =>	'Extracción de carbón lignito'],
            ['codigo' => '0610','nombre' =>	'Extracción de petróleo crudo'],
            ['codigo' => '0620','nombre' =>	'Extracción de gas natural'],
            ['codigo' => '0710','nombre' =>	'Extracción de minerales de hierro'],
            ['codigo' => '0721','nombre' =>	'Extracción de minerales de uranio y de torio'],
            ['codigo' => '0722','nombre' =>	'Extracción de oro y otros metales preciosos'],
            ['codigo' => '0723','nombre' =>	'Extracción de minerales de níquel'],
            ['codigo' => '0729','nombre' =>	'Extracción de otros minerales metalíferos no ferrosos n.c.p.'],
            ['codigo' => '0811','nombre' =>	'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita'],
            ['codigo' => '0812','nombre' =>	'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas'],
            ['codigo' => '0820','nombre' =>	'Extracción de esmeraldas, piedras preciosas y semipreciosas'],
            ['codigo' => '0891','nombre' =>	'Extracción de minerales para la fabricación de abonos y productos químicos'],
            ['codigo' => '0892','nombre' =>	'Extracción de halita (sal)'],
            ['codigo' => '0899','nombre' =>	'Extracción de otros minerales no metálicos n.c.p.'],
            ['codigo' => '0910','nombre' =>	'Actividades de apoyo para la extracción de petróleo y de gas natural'],
            ['codigo' => '0990','nombre' =>	'Actividades de apoyo para otras actividades de explotación de minas y canteras'],
            ['codigo' => '1011','nombre' =>	'Procesamiento y conservación de carne y productos cárnicos'],
            ['codigo' => '1012','nombre' =>	'Procesamiento y conservación de pescados, crustáceos y moluscos'],
            ['codigo' => '1020','nombre' =>	'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos'],
            ['codigo' => '1030','nombre' =>	'Elaboración de aceites y grasas de origen vegetal y animal'],
            ['codigo' => '1040','nombre' =>	'Elaboración de productos lácteos'],
            ['codigo' => '1051','nombre' =>	'Elaboración de productos de molinería'],
            ['codigo' => '1052','nombre' =>	'Elaboración de almidones y productos derivados del almidón'],
            ['codigo' => '1061','nombre' =>	'Trilla de café'],
            ['codigo' => '1062','nombre' =>	'Descafeinado, tostión y molienda del café'],
            ['codigo' => '1063','nombre' =>	'Otros derivados del café'],
            ['codigo' => '1071','nombre' =>	'Elaboración y refinación de azúcar'],
            ['codigo' => '1072','nombre' =>	'Elaboración de panela'],
            ['codigo' => '1081','nombre' =>	'Elaboración de productos de panadería'],
            ['codigo' => '1082','nombre' =>	'Elaboración de cacao, chocolate y productos de confitería'],
            ['codigo' => '1083','nombre' =>	'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares'],
            ['codigo' => '1084','nombre' =>	'Elaboración de comidas y platos preparados'],
            ['codigo' => '1089','nombre' =>	'Elaboración de otros productos alimenticios n.c.p.'],
            ['codigo' => '1090','nombre' =>	'Elaboración de alimentos preparados para animales'],
            ['codigo' => '1101','nombre' =>	'Destilación, rectificación y mezcla de bebidas alcohólicas'],
            ['codigo' => '1102','nombre' =>	'Elaboración de bebidas fermentadas no destiladas'],
            ['codigo' => '1103','nombre' =>	'Producción de malta, elaboración de cervezas y otras bebidas malteadas'],
            ['codigo' => '1104','nombre' =>	'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas'],
            ['codigo' => '1200','nombre' =>	'Elaboración de productos de tabaco'],
            ['codigo' => '1311','nombre' =>	'Preparación e hilatura de fibras textiles'],
            ['codigo' => '1312','nombre' =>	'Tejeduría de productos textiles'],
            ['codigo' => '1313','nombre' =>	'Acabado de productos textiles'],
            ['codigo' => '1391','nombre' =>	'Fabricación de tejidos de punto y ganchillo'],
            ['codigo' => '1392','nombre' =>	'Confección de artículos con materiales textiles, excepto prendas de vestir'],
            ['codigo' => '1393','nombre' =>	'Fabricación de tapetes y alfombras para pisos'],
            ['codigo' => '1394','nombre' =>	'Fabricación de cuerdas, cordeles, cables, bramantes y redes'],
            ['codigo' => '1399','nombre' =>	'Fabricación de otros artículos textiles n.c.p.'],
            ['codigo' => '1410','nombre' =>	'Confección de prendas de vestir, excepto prendas de piel'],
            ['codigo' => '1420','nombre' =>	'Fabricación de artículos de piel'],
            ['codigo' => '1430','nombre' =>	'Fabricación de artículos de punto y ganchillo'],
            ['codigo' => '1511','nombre' =>	'Curtido y recurtido de cueros; recurtido y teñido de pieles'],
            ['codigo' => '1512','nombre' =>	'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería'],
            ['codigo' => '1513','nombre' =>	'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales'],
            ['codigo' => '1521','nombre' =>	'Fabricación de calzado de cuero y piel, con cualquier tipo de suela'],
            ['codigo' => '1522','nombre' =>	'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel'],
            ['codigo' => '1523','nombre' =>	'Fabricación de partes del calzado'],
            ['codigo' => '1610','nombre' =>	'Aserrado, acepillado e impregnación de la madera'],
            ['codigo' => '1620','nombre' =>	'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles'],
            ['codigo' => '1630','nombre' =>	'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción'],
            ['codigo' => '1640','nombre' =>	'Fabricación de recipientes de madera'],
            ['codigo' => '1690','nombre' =>	'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería'],
            ['codigo' => '1701','nombre' =>	'Fabricación de pulpas (pastas) celulósicas; papel y cartón'],
            ['codigo' => '1702','nombre' =>	'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.'],
            ['codigo' => '1709','nombre' =>	'Fabricación de otros artículos de papel y cartón'],
            ['codigo' => '1811','nombre' =>	'Actividades de impresión'],
            ['codigo' => '1812','nombre' =>	'Actividades de servicios relacionados con la impresión'],
            ['codigo' => '1820','nombre' =>	'Producción de copias a partir de grabaciones originales '],
            ['codigo' => '1910','nombre' =>	'Fabricación de productos de hornos de coque'],
            ['codigo' => '1921','nombre' =>	'Fabricación de productos de la refinación del petróleo'],
            ['codigo' => '1922','nombre' =>	'Actividad de mezcla de combustibles'],
            ['codigo' => '2011','nombre' =>	'Fabricación de sustancias y productos químicos básicos'],
            ['codigo' => '2012','nombre' =>	'Fabricación de abonos y compuestos inorgánicos nitrogenados'],
            ['codigo' => '2013','nombre' =>	'Fabricación de plásticos en formas primarias'],
            ['codigo' => '2014','nombre' =>	'Fabricación de caucho sintético en formas primarias'],
            ['codigo' => '2021','nombre' =>	'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'],
            ['codigo' => '2022','nombre' =>	'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas'],
            ['codigo' => '2023','nombre' =>	'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador'],
            ['codigo' => '2029','nombre' =>	'Fabricación de otros productos químicos n.c.p.'],
            ['codigo' => '2030','nombre' =>	'Fabricación de fibras sintéticas y artificiales'],
            ['codigo' => '2100','nombre' =>	'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico'],
            ['codigo' => '2211','nombre' =>	'Fabricación de llantas y neumáticos de caucho'],
            ['codigo' => '2212','nombre' =>	'Reencauche de llantas usadas'],
            ['codigo' => '2219','nombre' =>	'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.'],
            ['codigo' => '2221','nombre' =>	'Fabricación de formas básicas de plástico'],
            ['codigo' => '2229','nombre' =>	'Fabricación de artículos de plástico n.c.p.'],
            ['codigo' => '2310','nombre' =>	'Fabricación de vidrio y productos de vidrio'],
            ['codigo' => '2391','nombre' =>	'Fabricación de productos refractarios'],
            ['codigo' => '2392','nombre' =>	'Fabricación de materiales de arcilla para la construcción'],
            ['codigo' => '2393','nombre' =>	'Fabricación de otros productos de cerámica y porcelana'],
            ['codigo' => '2394','nombre' =>	'Fabricación de cemento, cal y yeso'],
            ['codigo' => '2395','nombre' =>	'Fabricación de artículos de hormigón, cemento y yeso'],
            ['codigo' => '2396','nombre' =>	'Corte, tallado y acabado de la piedra'],
            ['codigo' => '2399','nombre' =>	'Fabricación de otros productos minerales no metálicos n.c.p.'],
            ['codigo' => '2410','nombre' =>	'Industrias básicas de hierro y de acero'],
            ['codigo' => '2421','nombre' =>	'Industrias básicas de metales preciosos'],
            ['codigo' => '2429','nombre' =>	'Industrias básicas de otros metales no ferrosos'],
            ['codigo' => '2431','nombre' =>	'Fundición de hierro y de acero'],
            ['codigo' => '2432','nombre' =>	'Fundición de metales no ferrosos '],
            ['codigo' => '2511','nombre' =>	'Fabricación de productos metálicos para uso estructural'],
            ['codigo' => '2512','nombre' =>	'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías'],
            ['codigo' => '2513','nombre' =>	'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central'],
            ['codigo' => '2520','nombre' =>	'Fabricación de armas y municiones'],
            ['codigo' => '2591','nombre' =>	'Forja, prensado, estampado y laminado de metal; pulvimetalurgia'],
            ['codigo' => '2592','nombre' =>	'Tratamiento y revestimiento de metales; mecanizado'],
            ['codigo' => '2593','nombre' =>	'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería'],
            ['codigo' => '2599','nombre' =>	'Fabricación de otros productos elaborados de metal n.c.p.'],
            ['codigo' => '2610','nombre' =>	'Fabricación de componentes y tableros electrónicos'],
            ['codigo' => '2620','nombre' =>	'Fabricación de computadoras y de equipo periférico'],
            ['codigo' => '2630','nombre' =>	'Fabricación de equipos de comunicación'],
            ['codigo' => '2640','nombre' =>	'Fabricación de aparatos electrónicos de consumo'],
            ['codigo' => '2651','nombre' =>	'Fabricación de equipo de medición, prueba, navegación y control'],
            ['codigo' => '2652','nombre' =>	'Fabricación de relojes'],
            ['codigo' => '2660','nombre' =>	'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico'],
            ['codigo' => '2670','nombre' =>	'Fabricación de instrumentos ópticos y equipo fotográfico'],
            ['codigo' => '2680','nombre' =>	'Fabricación de medios magnéticos y ópticos para almacenamiento de datos'],
            ['codigo' => '2711','nombre' =>	'Fabricación de motores, generadores y transformadores eléctricos'],
            ['codigo' => '2712','nombre' =>	'Fabricación de aparatos de distribución y control de la energía eléctrica'],
            ['codigo' => '2720','nombre' =>	'Fabricación de pilas, baterías y acumuladores eléctricos'],
            ['codigo' => '2731','nombre' =>	'Fabricación de hilos y cables eléctricos y de fibra óptica'],
            ['codigo' => '2732','nombre' =>	'Fabricación de dispositivos de cableado'],
            ['codigo' => '2740','nombre' =>	'Fabricación de equipos eléctricos de iluminación'],
            ['codigo' => '2750','nombre' =>	'Fabricación de aparatos de uso doméstico'],
            ['codigo' => '2790','nombre' =>	'Fabricación de otros tipos de equipo eléctrico n.c.p.'],
            ['codigo' => '2811','nombre' =>	'Fabricación de motores, turbinas, y partes para motores de combustión interna'],
            ['codigo' => '2812','nombre' =>	'Fabricación de equipos de potencia hidráulica y neumática'],
            ['codigo' => '2813','nombre' =>	'Fabricación de otras bombas, compresores, grifos y válvulas'],
            ['codigo' => '2814','nombre' =>	'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'],
            ['codigo' => '2815','nombre' =>	'Fabricación de hornos, hogares y quemadores industriales'],
            ['codigo' => '2816','nombre' =>	'Fabricación de equipo de elevación y manipulación'],
            ['codigo' => '2817','nombre' =>	'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)'],
            ['codigo' => '2818','nombre' =>	'Fabricación de herramientas manuales con motor'],
            ['codigo' => '2819','nombre' =>	'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.'],
            ['codigo' => '2821','nombre' =>	'Fabricación de maquinaria agropecuaria y forestal'],
            ['codigo' => '2822','nombre' =>	'Fabricación de máquinas formadoras de metal y de máquinas herramienta'],
            ['codigo' => '2823','nombre' =>	'Fabricación de maquinaria para la metalurgia'],
            ['codigo' => '2824','nombre' =>	'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción'],
            ['codigo' => '2825','nombre' =>	'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'],
            ['codigo' => '2826','nombre' =>	'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'],
            ['codigo' => '2829','nombre' =>	'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.'],
            ['codigo' => '2910','nombre' =>	'Fabricación de vehículos automotores y sus motores'],
            ['codigo' => '2920','nombre' =>	'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques '],
            ['codigo' => '2930','nombre' =>	'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'],
            ['codigo' => '3011','nombre' =>	'Construcción de barcos y de estructuras flotantes'],
            ['codigo' => '3012','nombre' =>	'Construcción de embarcaciones de recreo y deporte'],
            ['codigo' => '3020','nombre' =>	'Fabricación de locomotoras y de material rodante para ferrocarriles'],
            ['codigo' => '3030','nombre' =>	'Fabricación de aeronaves, naves espaciales y de maquinaria conexa'],
            ['codigo' => '3040','nombre' =>	'Fabricación de vehículos militares de combate'],
            ['codigo' => '3091','nombre' =>	'Fabricación de motocicletas'],
            ['codigo' => '3092','nombre' =>	'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad'],
            ['codigo' => '3099','nombre' =>	'Fabricación de otros tipos de equipo de transporte n.c.p.'],
            ['codigo' => '3110','nombre' =>	'Fabricación de muebles '],
            ['codigo' => '3120','nombre' =>	'Fabricación de colchones y somieres'],
            ['codigo' => '3210','nombre' =>	'Fabricación de joyas, bisutería y artículos conexos'],
            ['codigo' => '3220','nombre' =>	'Fabricación de instrumentos musicales'],
            ['codigo' => '3230','nombre' =>	'Fabricación de artículos y equipo para la práctica del deporte'],
            ['codigo' => '3240','nombre' =>	'Fabricación de juegos, juguetes y rompecabezas'],
            ['codigo' => '3250','nombre' =>	'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)'],
            ['codigo' => '3290','nombre' =>	'Otras industrias manufactureras n.c.p.'],
            ['codigo' => '3311','nombre' =>	'Mantenimiento y reparación especializado de productos elaborados en metal'],
            ['codigo' => '3312','nombre' =>	'Mantenimiento y reparación especializado de maquinaria y equipo'],
            ['codigo' => '3313','nombre' =>	'Mantenimiento y reparación especializado de equipo electrónico y óptico'],
            ['codigo' => '3314','nombre' =>	'Mantenimiento y reparación especializado de equipo eléctrico'],
            ['codigo' => '3315','nombre' =>	'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas'],
            ['codigo' => '3319','nombre' =>	'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.'],
            ['codigo' => '3320','nombre' =>	'Instalación especializada de maquinaria y equipo industrial '],
            ['codigo' => '3511','nombre' =>	'Generación de energía eléctrica'],
            ['codigo' => '3512','nombre' =>	'Transmisión de energía eléctrica'],
            ['codigo' => '3513','nombre' =>	'Distribución de energía eléctrica'],
            ['codigo' => '3514','nombre' =>	'Comercialización de energía eléctrica'],
            ['codigo' => '3520','nombre' =>	'Producción de gas; distribución de combustibles gaseosos por tuberías'],
            ['codigo' => '3530','nombre' =>	'Suministro de vapor y aire acondicionado'],
            ['codigo' => '3600','nombre' =>	'Captación, tratamiento y distribución de agua'],
            ['codigo' => '3700','nombre' =>	'Evacuación y tratamiento de aguas residuales'],
            ['codigo' => '3811','nombre' =>	'Recolección de desechos no peligrosos'],
            ['codigo' => '3812','nombre' =>	'Recolección de desechos peligrosos'],
            ['codigo' => '3821','nombre' =>	'Tratamiento y disposición de desechos no peligrosos'],
            ['codigo' => '3822','nombre' =>	'Tratamiento y disposición de desechos peligrosos'],
            ['codigo' => '3830','nombre' =>	'Recuperación de materiales'],
            ['codigo' => '3900','nombre' =>	'Actividades de saneamiento ambiental y otros servicios de gestión de desechos'],
            ['codigo' => '4111','nombre' =>	'Construcción de edificios residenciales'],
            ['codigo' => '4112','nombre' =>	'Construcción de edificios no residenciales'],
            ['codigo' => '4210','nombre' =>	'Construcción de carreteras y vías de ferrocarril'],
            ['codigo' => '4220','nombre' =>	'Construcción de proyectos de servicio público'],
            ['codigo' => '4290','nombre' =>	'Construcción de otras obras de ingeniería civil'],
            ['codigo' => '4311','nombre' =>	'Demolición'],
            ['codigo' => '4312','nombre' =>	'Preparación del terreno'],
            ['codigo' => '4321','nombre' =>	'Instalaciones eléctricas'],
            ['codigo' => '4322','nombre' =>	'Instalaciones de fontanería, calefacción y aire acondicionado'],
            ['codigo' => '4329','nombre' =>	'Otras instalaciones especializadas'],
            ['codigo' => '4330','nombre' =>	'Terminación y acabado de edificios y obras de ingeniería civil'],
            ['codigo' => '4390','nombre' =>	'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil'],
            ['codigo' => '4511','nombre' =>	'Comercio de vehículos automotores nuevos'],
            ['codigo' => '4512','nombre' =>	'Comercio de vehículos automotores usados'],
            ['codigo' => '4520','nombre' =>	'Mantenimiento y reparación de vehículos automotores'],
            ['codigo' => '4530','nombre' =>	'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'],
            ['codigo' => '4541','nombre' =>	'Comercio de motocicletas y de sus partes, piezas y accesorios'],
            ['codigo' => '4542','nombre' =>	'Mantenimiento y reparación de motocicletas y de sus partes y piezas'],
            ['codigo' => '4610','nombre' =>	'Comercio al por mayor a cambio de una retribución o por contrata'],
            ['codigo' => '4620','nombre' =>	'Comercio al por mayor de materias primas agropecuarias; animales vivos'],
            ['codigo' => '4631','nombre' =>	'Comercio al por mayor de productos alimenticios'],
            ['codigo' => '4632','nombre' =>	'Comercio al por mayor de bebidas y tabaco'],
            ['codigo' => '4641','nombre' =>	'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico'],
            ['codigo' => '4642','nombre' =>	'Comercio al por mayor de prendas de vestir'],
            ['codigo' => '4643','nombre' =>	'Comercio al por mayor de calzado'],
            ['codigo' => '4644','nombre' =>	'Comercio al por mayor de aparatos y equipo de uso doméstico'],
            ['codigo' => '4645','nombre' =>	'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador'],
            ['codigo' => '4649','nombre' =>	'Comercio al por mayor de otros utensilios domésticos n.c.p.'],
            ['codigo' => '4651','nombre' =>	'Comercio al por mayor de computadores, equipo periférico y programas de informática'],
            ['codigo' => '4652','nombre' =>	'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones'],
            ['codigo' => '4653','nombre' =>	'Comercio al por mayor de maquinaria y equipo agropecuarios'],
            ['codigo' => '4659','nombre' =>	'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.'],
            ['codigo' => '4661','nombre' =>	'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos'],
            ['codigo' => '4662','nombre' =>	'Comercio al por mayor de metales y productos metalíferos'],
            ['codigo' => '4663','nombre' =>	'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción'],
            ['codigo' => '4664','nombre' =>	'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario'],
            ['codigo' => '4665','nombre' =>	'Comercio al por mayor de desperdicios, desechos y chatarra'],
            ['codigo' => '4669','nombre' =>	'Comercio al por mayor de otros productos n.c.p.'],
            ['codigo' => '4690','nombre' =>	'Comercio al por mayor no especializado'],
            ['codigo' => '4711','nombre' =>	'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco'],
            ['codigo' => '4719','nombre' =>	'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco'],
            ['codigo' => '4721','nombre' =>	'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados'],
            ['codigo' => '4722','nombre' =>	'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados'],
            ['codigo' => '4723','nombre' =>	'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados'],
            ['codigo' => '4724','nombre' =>	'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados'],
            ['codigo' => '4729','nombre' =>	'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados'],
            ['codigo' => '4731','nombre' =>	'Comercio al por menor de combustible para automotores'],
            ['codigo' => '4732','nombre' =>	'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores'],
            ['codigo' => '4741','nombre' =>	'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados'],
            ['codigo' => '4742','nombre' =>	'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados'],
            ['codigo' => '4751','nombre' =>	'Comercio al por menor de productos textiles en establecimientos especializados'],
            ['codigo' => '4752','nombre' =>	'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados'],
            ['codigo' => '4753','nombre' =>	'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados'],
            ['codigo' => '4754','nombre' =>	'Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación'],
            ['codigo' => '4755','nombre' =>	'Comercio al por menor de artículos y utensilios de uso doméstico'],
            ['codigo' => '4759','nombre' =>	'Comercio al por menor de otros artículos domésticos en establecimientos especializados'],
            ['codigo' => '4761','nombre' =>	'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados'],
            ['codigo' => '4762','nombre' =>	'Comercio al por menor de artículos deportivos, en establecimientos especializados '],
            ['codigo' => '4769','nombre' =>	'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados'],
            ['codigo' => '4771','nombre' =>	'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados'],
            ['codigo' => '4772','nombre' =>	'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.'],
            ['codigo' => '4773','nombre' =>	'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados'],
            ['codigo' => '4774','nombre' =>	'Comercio al por menor de otros productos nuevos en establecimientos especializados'],
            ['codigo' => '4775','nombre' =>	'Comercio al por menor de artículos de segunda mano'],
            ['codigo' => '4781','nombre' =>	'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles'],
            ['codigo' => '4782','nombre' =>	'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles'],
            ['codigo' => '4789','nombre' =>	'Comercio al por menor de otros productos en puestos de venta móviles'],
            ['codigo' => '4791','nombre' =>	'Comercio al por menor realizado a través de Internet'],
            ['codigo' => '4792','nombre' =>	'Comercio al por menor realizado a través de casas de venta o por correo'],
            ['codigo' => '4799','nombre' =>	'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.'],
            ['codigo' => '4911','nombre' =>	'Transporte férreo de pasajeros'],
            ['codigo' => '4912','nombre' =>	'Transporte férreo de carga '],
            ['codigo' => '4921','nombre' =>	'Transporte de pasajeros'],
            ['codigo' => '4922','nombre' =>	'Transporte mixto'],
            ['codigo' => '4923','nombre' =>	'Transporte de carga por carretera'],
            ['codigo' => '4930','nombre' =>	'Transporte por tuberías'],
            ['codigo' => '5011','nombre' =>	'Transporte de pasajeros marítimo y de cabotaje '],
            ['codigo' => '5012','nombre' =>	'Transporte de carga marítimo y de cabotaje '],
            ['codigo' => '5021','nombre' =>	'Transporte fluvial de pasajeros'],
            ['codigo' => '5022','nombre' =>	'Transporte fluvial de carga'],
            ['codigo' => '5111','nombre' =>	'Transporte aéreo nacional de pasajeros '],
            ['codigo' => '5112','nombre' =>	'Transporte aéreo internacional de pasajeros '],
            ['codigo' => '5121','nombre' =>	'Transporte aéreo nacional de carga '],
            ['codigo' => '5122','nombre' =>	'Transporte aéreo internacional de carga '],
            ['codigo' => '5210','nombre' =>	'Almacenamiento y depósito'],
            ['codigo' => '5221','nombre' =>	'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre'],
            ['codigo' => '5222','nombre' =>	'Actividades de puertos y servicios complementarios para el transporte acuático'],
            ['codigo' => '5223','nombre' =>	'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo'],
            ['codigo' => '5224','nombre' =>	'Manipulación de carga'],
            ['codigo' => '5229','nombre' =>	'Otras actividades complementarias al transporte'],
            ['codigo' => '5310','nombre' =>	'Actividades postales nacionales'],
            ['codigo' => '5320','nombre' =>	'Actividades de mensajería'],
            ['codigo' => '5511','nombre' =>	'Alojamiento en hoteles '],
            ['codigo' => '5512','nombre' =>	'Alojamiento en apartahoteles'],
            ['codigo' => '5513','nombre' =>	'Alojamiento en centros vacacionales '],
            ['codigo' => '5514','nombre' =>	'Alojamiento rural'],
            ['codigo' => '5519','nombre' =>	'Otros tipos de alojamientos para visitantes'],
            ['codigo' => '5520','nombre' =>	'Actividades de zonas de camping y parques para vehículos recreacionales'],
            ['codigo' => '5530','nombre' =>	'Servicio por horas '],
            ['codigo' => '5590','nombre' =>	'Otros tipos de alojamiento n.c.p.'],
            ['codigo' => '5611','nombre' =>	'Expendio a la mesa de comidas preparadas'],
            ['codigo' => '5612','nombre' =>	'Expendio por autoservicio de comidas preparadas'],
            ['codigo' => '5613','nombre' =>	'Expendio de comidas preparadas en cafeterías'],
            ['codigo' => '5619','nombre' =>	'Otros tipos de expendio de comidas preparadas n.c.p.'],
            ['codigo' => '5621','nombre' =>	'Catering para eventos'],
            ['codigo' => '5629','nombre' =>	'Actividades de otros servicios de comidas'],
            ['codigo' => '5630','nombre' =>	'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento'],
            ['codigo' => '5811','nombre' =>	'Edición de libros'],
            ['codigo' => '5812','nombre' =>	'Edición de directorios y listas de correo'],
            ['codigo' => '5813','nombre' =>	'Edición de periódicos, revistas y otras publicaciones periódicas'],
            ['codigo' => '5819','nombre' =>	'Otros trabajos de edición'],
            ['codigo' => '5820','nombre' =>	'Edición de programas de informática (software)'],
            ['codigo' => '5911','nombre' =>	'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'],
            ['codigo' => '5912','nombre' =>	'Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'],
            ['codigo' => '5913','nombre' =>	'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión'],
            ['codigo' => '5914','nombre' =>	'Actividades de exhibición de películas cinematográficas y videos'],
            ['codigo' => '5920','nombre' =>	'Actividades de grabación de sonido y edición de música'],
            ['codigo' => '6010','nombre' =>	'Actividades de programación y transmisión en el servicio de radiodifusión sonora'],
            ['codigo' => '6020','nombre' =>	'Actividades de programación y transmisión de televisión'],
            ['codigo' => '6110','nombre' =>	'Actividades de telecomunicaciones alámbricas'],
            ['codigo' => '6120','nombre' =>	'Actividades de telecomunicaciones inalámbricas'],
            ['codigo' => '6130','nombre' =>	'Actividades de telecomunicación satelital'],
            ['codigo' => '6190','nombre' =>	'Otras actividades de telecomunicaciones'],
            ['codigo' => '6201','nombre' =>	'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)'],
            ['codigo' => '6202','nombre' =>	'Actividades de consultoría informática y actividades de administración de instalaciones informáticas'],
            ['codigo' => '6209','nombre' =>	'Otras actividades de tecnologías de información y actividades de servicios informáticos'],
            ['codigo' => '6311','nombre' =>	'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas'],
            ['codigo' => '6312','nombre' =>	'Portales web'],
            ['codigo' => '6391','nombre' =>	'Actividades de agencias de noticias'],
            ['codigo' => '6399','nombre' =>	'Otras actividades de servicio de información n.c.p.'],
            ['codigo' => '6411','nombre' =>	'Banco Central'],
            ['codigo' => '6412','nombre' =>	'Bancos comerciales'],
            ['codigo' => '6421','nombre' =>	'Actividades de las corporaciones financieras'],
            ['codigo' => '6422','nombre' =>	'Actividades de las compañías de financiamiento'],
            ['codigo' => '6423','nombre' =>	'Banca de segundo piso'],
            ['codigo' => '6424','nombre' =>	'Actividades de las cooperativas financieras'],
            ['codigo' => '6431','nombre' =>	'Fideicomisos, fondos y entidades financieras similares'],
            ['codigo' => '6432','nombre' =>	'Fondos de cesantías'],
            ['codigo' => '6491','nombre' =>	'Leasing financiero (arrendamiento financiero)'],
            ['codigo' => '6492','nombre' =>	'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario'],
            ['codigo' => '6493','nombre' =>	'Actividades de compra de cartera o factoring'],
            ['codigo' => '6494','nombre' =>	'Otras actividades de distribución de fondos'],
            ['codigo' => '6495','nombre' =>	'Instituciones especiales oficiales'],
            ['codigo' => '6499','nombre' =>	'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.'],
            ['codigo' => '6511','nombre' =>	'Seguros generales '],
            ['codigo' => '6512','nombre' =>	'Seguros de vida'],
            ['codigo' => '6513','nombre' =>	'Reaseguros'],
            ['codigo' => '6514','nombre' =>	'Capitalización'],
            ['codigo' => '6521','nombre' =>	'Servicios de seguros sociales de salud'],
            ['codigo' => '6522','nombre' =>	'Servicios de seguros sociales de riesgos profesionales'],
            ['codigo' => '6531','nombre' =>	'Régimen de prima media con prestación definida (RPM)'],
            ['codigo' => '6532','nombre' =>	'Régimen de ahorro individual (RAI)'],
            ['codigo' => '6611','nombre' =>	'Administración de mercados financieros'],
            ['codigo' => '6612','nombre' =>	'Corretaje de valores y de contratos de productos básicos'],
            ['codigo' => '6613','nombre' =>	'Otras actividades relacionadas con el mercado de valores'],
            ['codigo' => '6614','nombre' =>	'Actividades de las casas de cambio'],
            ['codigo' => '6615','nombre' =>	'Actividades de los profesionales de compra y venta de divisas'],
            ['codigo' => '6619','nombre' =>	'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.'],
            ['codigo' => '6621','nombre' =>	'Actividades de agentes y corredores de seguros'],
            ['codigo' => '6629','nombre' =>	'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares'],
            ['codigo' => '6630','nombre' =>	'Actividades de administración de fondos'],
            ['codigo' => '6810','nombre' =>	'Actividades inmobiliarias realizadas con bienes propios o arrendados'],
            ['codigo' => '6820','nombre' =>	'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata '],
            ['codigo' => '6910','nombre' =>	'Actividades jurídicas'],
            ['codigo' => '6920','nombre' =>	'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria'],
            ['codigo' => '7010','nombre' =>	'Actividades de administración empresarial'],
            ['codigo' => '7020','nombre' =>	'Actividades de consultaría de gestión'],
            ['codigo' => '7110','nombre' =>	'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica'],
            ['codigo' => '7120','nombre' =>	'Ensayos y análisis técnicos'],
            ['codigo' => '7210','nombre' =>	'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería '],
            ['codigo' => '7220','nombre' =>	'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'],
            ['codigo' => '7310','nombre' =>	'Publicidad'],
            ['codigo' => '7320','nombre' =>	'Estudios de mercado y realización de encuestas de opinión pública'],
            ['codigo' => '7410','nombre' =>	'Actividades especializadas de diseño '],
            ['codigo' => '7420','nombre' =>	'Actividades de fotografía'],
            ['codigo' => '7490','nombre' =>	'Otras actividades profesionales, científicas y técnicas n.c.p.'],
            ['codigo' => '7500','nombre' =>	'Actividades veterinarias'],
            ['codigo' => '7710','nombre' =>	'Alquiler y arrendamiento de vehículos automotores'],
            ['codigo' => '7721','nombre' =>	'Alquiler y arrendamiento de equipo recreativo y deportivo'],
            ['codigo' => '7722','nombre' =>	'Alquiler de videos y discos '],
            ['codigo' => '7729','nombre' =>	'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.'],
            ['codigo' => '7730','nombre' =>	'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.'],
            ['codigo' => '7740','nombre' =>	'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'],
            ['codigo' => '7810','nombre' =>	'Actividades de agencias de empleo'],
            ['codigo' => '7820','nombre' =>	'Actividades de agencias de empleo temporal'],
            ['codigo' => '7830','nombre' =>	'Otras actividades de suministro de recurso humano'],
            ['codigo' => '7911','nombre' =>	'Actividades de las agencias de viaje'],
            ['codigo' => '7912','nombre' =>	'Actividades de operadores turísticos'],
            ['codigo' => '7990','nombre' =>	'Otros servicios de reserva y actividades relacionadas'],
            ['codigo' => '8010','nombre' =>	'Actividades de seguridad privada'],
            ['codigo' => '8020','nombre' =>	'Actividades de servicios de sistemas de seguridad'],
            ['codigo' => '8030','nombre' =>	'Actividades de detectives e investigadores privados'],
            ['codigo' => '8110','nombre' =>	'Actividades combinadas de apoyo a instalaciones'],
            ['codigo' => '8121','nombre' =>	'Limpieza general interior de edificios'],
            ['codigo' => '8129','nombre' =>	'Otras actividades de limpieza de edificios e instalaciones industriales'],
            ['codigo' => '8130','nombre' =>	'Actividades de paisajismo y servicios de mantenimiento conexos'],
            ['codigo' => '8211','nombre' =>	'Actividades combinadas de servicios administrativos de oficina'],
            ['codigo' => '8219','nombre' =>	'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina'],
            ['codigo' => '8220','nombre' =>	'Actividades de centros de llamadas (Call center)'],
            ['codigo' => '8230','nombre' =>	'Organización de convenciones y eventos comerciales'],
            ['codigo' => '8291','nombre' =>	'Actividades de agencias de cobranza y oficinas de calificación crediticia'],
            ['codigo' => '8292','nombre' =>	'Actividades de envase y empaque'],
            ['codigo' => '8299','nombre' =>	'Otras actividades de servicio de apoyo a las empresas n.c.p.'],
            ['codigo' => '8411','nombre' =>	'Actividades legislativas de la administración pública'],
            ['codigo' => '8412','nombre' =>	'Actividades ejecutivas de la administración pública'],
            ['codigo' => '8413','nombre' =>	'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social '],
            ['codigo' => '8414','nombre' =>	'Actividades reguladoras y facilitadoras de la actividad económica'],
            ['codigo' => '8415','nombre' =>	'Actividades de los otros órganos de control'],
            ['codigo' => '8421','nombre' =>	'Relaciones exteriores '],
            ['codigo' => '8422','nombre' =>	'Actividades de defensa'],
            ['codigo' => '8423','nombre' =>	'Orden público y actividades de seguridad'],
            ['codigo' => '8424','nombre' =>	'Administración de justicia'],
            ['codigo' => '8430','nombre' =>	'Actividades de planes de seguridad social de afiliación obligatoria'],
            ['codigo' => '8511','nombre' =>	'Educación de la primera infancia'],
            ['codigo' => '8512','nombre' =>	'Educación preescolar'],
            ['codigo' => '8513','nombre' =>	'Educación básica primaria'],
            ['codigo' => '8521','nombre' =>	'Educación básica secundaria '],
            ['codigo' => '8522','nombre' =>	'Educación media académica'],
            ['codigo' => '8523','nombre' =>	'Educación media técnica y de formación laboral'],
            ['codigo' => '8530','nombre' =>	'Establecimientos que combinan diferentes niveles de educación '],
            ['codigo' => '8541','nombre' =>	'Educación técnica profesional'],
            ['codigo' => '8542','nombre' =>	'Educación tecnológica'],
            ['codigo' => '8543','nombre' =>	'Educación de instituciones universitarias o de escuelas tecnológicas'],
            ['codigo' => '8544','nombre' =>	'Educación de universidades'],
            ['codigo' => '8551','nombre' =>	'Formación académica no formal '],
            ['codigo' => '8552','nombre' =>	'Enseñanza deportiva y recreativa'],
            ['codigo' => '8553','nombre' =>	'Enseñanza cultural'],
            ['codigo' => '8559','nombre' =>	'Otros tipos de educación n.c.p.'],
            ['codigo' => '8560','nombre' =>	'Actividades de apoyo a la educación'],
            ['codigo' => '8610','nombre' =>	'Actividades de hospitales y clínicas, con internación'],
            ['codigo' => '8621','nombre' =>	'Actividades de la práctica médica, sin internación'],
            ['codigo' => '8622','nombre' =>	'Actividades de la práctica odontológica'],
            ['codigo' => '8691','nombre' =>	'Actividades de apoyo diagnóstico'],
            ['codigo' => '8692','nombre' =>	'Actividades de apoyo terapéutico'],
            ['codigo' => '8699','nombre' =>	'Otras actividades de atención de la salud humana'],
            ['codigo' => '8710','nombre' =>	'Actividades de atención residencial medicalizada de tipo general'],
            ['codigo' => '8720','nombre' =>	'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas'],
            ['codigo' => '8730','nombre' =>	'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas'],
            ['codigo' => '8790','nombre' =>	'Otras actividades de atención en instituciones con alojamiento'],
            ['codigo' => '8810','nombre' =>	'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas'],
            ['codigo' => '8890','nombre' =>	'Otras actividades de asistencia social sin alojamiento'],
            ['codigo' => '9001','nombre' =>	'Creación literaria'],
            ['codigo' => '9002','nombre' =>	'Creación musical'],
            ['codigo' => '9003','nombre' =>	'Creación teatral'],
            ['codigo' => '9004','nombre' =>	'Creación audiovisual'],
            ['codigo' => '9005','nombre' =>	'Artes plásticas y visuales'],
            ['codigo' => '9006','nombre' =>	'Actividades teatrales'],
            ['codigo' => '9007','nombre' =>	'Actividades de espectáculos musicales en vivo'],
            ['codigo' => '9008','nombre' =>	'Otras actividades de espectáculos en vivo'],
            ['codigo' => '9101','nombre' =>	'Actividades de bibliotecas y archivos'],
            ['codigo' => '9102','nombre' =>	'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos'],
            ['codigo' => '9103','nombre' =>	'Actividades de jardines botánicos, zoológicos y reservas naturales'],
            ['codigo' => '9200','nombre' =>	'Actividades de juegos de azar y apuestas'],
            ['codigo' => '9311','nombre' =>	'Gestión de instalaciones deportivas'],
            ['codigo' => '9312','nombre' =>	'Actividades de clubes deportivos'],
            ['codigo' => '9319','nombre' =>	'Otras actividades deportivas'],
            ['codigo' => '9321','nombre' =>	'Actividades de parques de atracciones y parques temáticos'],
            ['codigo' => '9329','nombre' =>	'Otras actividades recreativas y de esparcimiento n.c.p.'],
            ['codigo' => '9411','nombre' =>	'Actividades de asociaciones empresariales y de empleadores'],
            ['codigo' => '9412','nombre' =>	'Actividades de asociaciones profesionales'],
            ['codigo' => '9420','nombre' =>	'Actividades de sindicatos de empleados'],
            ['codigo' => '9491','nombre' =>	'Actividades de asociaciones religiosas'],
            ['codigo' => '9492','nombre' =>	'Actividades de asociaciones políticas'],
            ['codigo' => '9499','nombre' =>	'Actividades de otras asociaciones n.c.p.'],
            ['codigo' => '9511','nombre' =>	'Mantenimiento y reparación de computadores y de equipo periférico'],
            ['codigo' => '9512','nombre' =>	'Mantenimiento y reparación de equipos de comunicación'],
            ['codigo' => '9521','nombre' =>	'Mantenimiento y reparación de aparatos electrónicos de consumo'],
            ['codigo' => '9522','nombre' =>	'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería '],
            ['codigo' => '9523','nombre' =>	'Reparación de calzado y artículos de cuero'],
            ['codigo' => '9524','nombre' =>	'Reparación de muebles y accesorios para el hogar'],
            ['codigo' => '9529','nombre' =>	'Mantenimiento y reparación de otros efectos personales y enseres domésticos'],
            ['codigo' => '9601','nombre' =>	'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel'],
            ['codigo' => '9602','nombre' =>	'Peluquería y otros tratamientos de belleza'],
            ['codigo' => '9603','nombre' =>	'Pompas fúnebres y actividades relacionadas'],
            ['codigo' => '9609','nombre' =>	'Otras actividades de servicios personales n.c.p.'],
            ['codigo' => '9700','nombre' =>	'Actividades de los hogares individuales como empleadores de personal doméstico'],
            ['codigo' => '9810','nombre' =>	'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio'],
            ['codigo' => '9820','nombre' =>	'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio'],
            ['codigo' => '9900','nombre' =>	'Actividades de organizaciones y entidades extraterritoriales'],

        ];

        CodigoCiiu::insert($codigos);
    }
}
