<?php

namespace Database\Seeders;

use App\Models\DetalleTributarioCT;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DetalleTributarioTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $impuestos = [
            ['codigo' => 1, 'nombre' => 'DECLARACIÓN DE RENTA - PERSONAS JURÍDICAS'],
            ['codigo' => 2, 'nombre' => 'PAGO 2A. CUOTA Y ANTICIPO 2A. CUOTA PUNTOS ADICIONALES'],
            ['codigo' => 3, 'nombre' => 'DECLARACIÓN DE IVA BIMESTRE 1'],
            ['codigo' => 4, 'nombre' => 'DECLARACIÓN DE IVA BIMESTRE 2'],
            ['codigo' => 5, 'nombre' => 'DECLARACIÓN DE IVA BIMESTRE 3'],
            ['codigo' => 6, 'nombre' => 'DECLARACIÓN DE IVA BIMESTRE 4'],
            ['codigo' => 7, 'nombre' => 'DECLARACIÓN DE IVA BIMESTRE 5'],
            ['codigo' => 8, 'nombre' => 'DECLARACIÓN DE IVA BIMESTRE 6'],
            ['codigo' => 9, 'nombre' => 'DECLARACIÓN DE IVA CUATRIMESTRE 1'],
            ['codigo' => 10, 'nombre' => 'DECLARACIÓN DE IVA CUATRIMESTRE 2'],
            ['codigo' => 11, 'nombre' => 'DECLARACIÓN DE IVA CUATRIMESTRE 3'],
            ['codigo' => 12, 'nombre' => 'DECLARACIÓN DE RENTA - PERSONAS NATURALES Y SUCESIONES ILÍQUIDAS'],
            ['codigo' => 13, 'nombre' => 'DECLARACIÓN ANUAL UNIFICADA SIMPLE'],
            ['codigo' => 14, 'nombre' => 'DECLARACIÓN DE IVA PRESTADORES DE SERVICIOS DESDE EL EXTERIOR ENERO - FEBRERO'],
            ['codigo' => 15, 'nombre' => 'DECLARACIÓN DE IVA PRESTADORES DE SERVICIOS DESDE EL EXTERIOR MARZO - ABRIL'],
            ['codigo' => 16, 'nombre' => 'DECLARACIÓN DE IVA PRESTADORES DE SERVICIOS DESDE EL EXTERIOR MAYO - JUNIO'],
            ['codigo' => 17, 'nombre' => 'DECLARACIÓN DE IVA PRESTADORES DE SERVICIOS DESDE EL EXTERIOR JULIO - AGOSTO'],
            ['codigo' => 18, 'nombre' => 'DECLARACIÓN DE IVA PRESTADORES DE SERVICIOS DESDE EL EXTERIOR SEPTIEMBRE - OCTUBRE'],
            ['codigo' => 19, 'nombre' => 'DECLARACIÓN DE IVA PRESTADORES DE SERVICIOS DESDE EL EXTERIOR NOVIEMBRE - DICIEMBRE'],
            ['codigo' => 20, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS ENERO'],
            ['codigo' => 21, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS FEBRERO'],
            ['codigo' => 22, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS MARZO'],
            ['codigo' => 23, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS ABRIL'],
            ['codigo' => 24, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS MAYO'],
            ['codigo' => 25, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS JUNIO'],
            ['codigo' => 26, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS JULIO'],
            ['codigo' => 27, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS AGOSTO'],
            ['codigo' => 28, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS SEPTIEMBRE'],
            ['codigo' => 29, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS OCTUBRE'],
            ['codigo' => 30, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS NOVIEMBRE'],
            ['codigo' => 31, 'nombre' => 'PRESENTACIÓN RETEFUENTE POR AGENTES DE RETENCIÓN CON MÁS DE 100 SUCURSALES O AGENCIAS DICIEMBRE'],
            ['codigo' => 32, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA ENERO'],
            ['codigo' => 33, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  FEBRERO'],
            ['codigo' => 34, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  MARZO'],
            ['codigo' => 35, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  ABRIL'],
            ['codigo' => 36, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  MAYO'],
            ['codigo' => 37, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  JUNIO'],
            ['codigo' => 38, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  JULIO'],
            ['codigo' => 39, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  AGOSTO'],
            ['codigo' => 40, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  SEPTIEMBRE'],
            ['codigo' => 41, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  OCTUBRE'],
            ['codigo' => 42, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  NOVIEMBRE'],
            ['codigo' => 43, 'nombre' => 'RETENCIÓN EN LA FUENTE Y AUTORRETENCIÓN RENTA  DICIEMBRE'],
            ['codigo' => 44, 'nombre' => 'DECLARACIÓN ANUAL CONSOLIDADA IVA SIMPLE'],
            ['codigo' => 45, 'nombre' => 'IMPUESTO AL PATRIMONIO'],
            ['codigo' => 46, 'nombre' => 'INFORMACIÓN EXOGENA GRANDES  CONTRIBUYENTES'],
            ['codigo' => 47, 'nombre' => 'INFORMACIÓN EXOGENA PERSONAS JURÍDICAS Y NATURALES'],
            ['codigo' => 48, 'nombre' => 'IMPUESTO GASOLINA Y ACPM ENERO'],
            ['codigo' => 49, 'nombre' => 'IMPUESTO GASOLINA Y ACPM FEBRERO'],
            ['codigo' => 50, 'nombre' => 'IMPUESTO GASOLINA Y ACPM MARZO'],
            ['codigo' => 51, 'nombre' => 'IMPUESTO GASOLINA Y ACPM ABRIL'],
            ['codigo' => 52, 'nombre' => 'IMPUESTO GASOLINA Y ACPM MAYO'],
            ['codigo' => 53, 'nombre' => 'IMPUESTO GASOLINA Y ACPM JUNIO'],
            ['codigo' => 54, 'nombre' => 'IMPUESTO GASOLINA Y ACPM JULIO'],
            ['codigo' => 55, 'nombre' => 'IMPUESTO GASOLINA Y ACPM AGOSTO'],
            ['codigo' => 56, 'nombre' => 'IMPUESTO GASOLINA Y ACPM SEPTIEMBRE'],
            ['codigo' => 57, 'nombre' => 'IMPUESTO GASOLINA Y ACPM OCTUBRE'],
            ['codigo' => 58, 'nombre' => 'IMPUESTO GASOLINA Y ACPM NOVIEMBRE'],
            ['codigo' => 59, 'nombre' => 'IMPUESTO GASOLINA Y ACPM DICIEMBRE'],
            ['codigo' => 60, 'nombre' => 'SUPERINTENDENCIA DE SOCIEDADES - ENVÍO ESTADOS FINANCIEROS A 31 DIC 2022'],
            ['codigo' => 61, 'nombre' => 'SUPERINTENDENCIA DE SOCIEDADES - PRÁCTICAS EMPRESARIALES'],
            ['codigo' => 62, 'nombre' => 'PRECIOS DE TRANSFERENCIA - ANTICIPO BIMESTRAL RÉGIMEN SIMPLE ENE - FEB'],
            ['codigo' => 63, 'nombre' => 'PRECIOS DE TRANSFERENCIA - ANTICIPO BIMESTRAL RÉGIMEN SIMPLE MAR - ABR'],
            ['codigo' => 64, 'nombre' => 'PRECIOS DE TRANSFERENCIA - ANTICIPO BIMESTRAL RÉGIMEN SIMPLE MAY - JUN'],
            ['codigo' => 65, 'nombre' => 'PRECIOS DE TRANSFERENCIA - ANTICIPO BIMESTRAL RÉGIMEN SIMPLE JUL - AGO'],
            ['codigo' => 66, 'nombre' => 'PRECIOS DE TRANSFERENCIA - ANTICIPO BIMESTRAL RÉGIMEN SIMPLE SEPT - OCT'],
            ['codigo' => 67, 'nombre' => 'PRECIOS DE TRANSFERENCIA - ANTICIPO BIMESTRAL RÉGIMEN SIMPLE NOV - DIC'],
            ['codigo' => 68, 'nombre' => 'PRECIOS DE TRANSFERENCIA - DECLARACIÓN Y DOCUMENTACION COMPROBATORIA'],
            ['codigo' => 69, 'nombre' => 'PRECIOS DE TRANSFERENCIA - INFORME MAESTRO'],
            ['codigo' => 70, 'nombre' => 'IMPUESTO NACIONAL AL CARBONO  ENE - FEB '],
            ['codigo' => 71, 'nombre' => 'IMPUESTO NACIONAL AL CARBONO  MAR - ABR '],
            ['codigo' => 72, 'nombre' => 'IMPUESTO NACIONAL AL CARBONO  MAY - JUN '],
            ['codigo' => 73, 'nombre' => 'IMPUESTO NACIONAL AL CARBONO  JUL - AGO '],
            ['codigo' => 74, 'nombre' => 'IMPUESTO NACIONAL AL CARBONO  SEPT - OCT '],
            ['codigo' => 75, 'nombre' => 'IMPUESTO NACIONAL AL CARBONO  NOV - DIC '],
            ['codigo' => 76, 'nombre' => 'IMPUESTO NACIONAL SOBRE PRODUCTOS PLÁSTICOS DE UN SOLO USO'],
            ['codigo' => 77, 'nombre' => 'IMPUESTO BEBIDAS  AZUCARADAS Y  COMESTIBLES ULTRAPROCESADOS INDUSTRIALMENTE'],
            ['codigo' => 78, 'nombre' => 'DECLARACIÓN ANUAL CONSOLIDADA DEL IMPUESTO A LAS VENTAS - IVA'],
            ['codigo' => 79, 'nombre' => 'PRIMER BIMESTRE'],
            ['codigo' => 80, 'nombre' => 'SEGUNDO BIMESTRE'],
            ['codigo' => 81, 'nombre' => 'TERCER BIMESTRE'],
            ['codigo' => 82, 'nombre' => 'CUARTO BIMESTRE'],
            ['codigo' => 83, 'nombre' => 'QUINTO BIMESTRE'],
            ['codigo' => 84, 'nombre' => 'SEXTO BIMESTRE'],
            ['codigo' => 85, 'nombre' => 'FECHA DE DECLARACIÓN Y PAGO ANUAL'],
            ['codigo' => 86, 'nombre' => 'ESTADOS FINANCIEROS FIN DE EJERCICIO'],
            ['codigo' => 87, 'nombre' => 'ESTADOS FINANCIEROS CONSOLIDADOS'],
            ['codigo' => 88, 'nombre' => 'ESTADOS FINANCIEROS COMBINADOS'],
            ['codigo' => 89, 'nombre' => 'INFORMACIÓN ESTADÍSTICA'],
            ['codigo' => 90, 'nombre' => 'DATOS PARA EL MINISTERIO'],
            ['codigo' => 91, 'nombre' => 'RENOVACIÓN MATRÍCULA MERCANTIL'],
            ['codigo' => 92, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO ENERO'],
            ['codigo' => 93, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO FEBRERO'],
            ['codigo' => 94, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO MARZO'],
            ['codigo' => 95, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO ABRIL'],
            ['codigo' => 96, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO MAYO'],
            ['codigo' => 97, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO JUNIO'],
            ['codigo' => 98, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO JULIO'],
            ['codigo' => 99, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO AGOSTO'],
            ['codigo' => 100, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO SEPTIEMBRE'],
            ['codigo' => 101, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO OCTUBRE'],
            ['codigo' => 102, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO NOVIEMBRE'],
            ['codigo' => 103, 'nombre' => 'DECLARACIÓN MENSUAL Y PAGO DICIEMBRE'],
            ['codigo' => 104, 'nombre' => 'PAGO 1A. CUOTA '],
            ['codigo' => 105, 'nombre' => 'DECLARACIÓN Y PAGO 2A. CUOTA'],
            ['codigo' => 106, 'nombre' => 'PAGO 3A. CUOTA'],
            ['codigo' => 107, 'nombre' => 'REGISTRO ÚNICO DE BENEFICIARIOS FINALES - ACTUALIZACIÓN'],
            ['codigo' => 108, 'nombre' => 'DECLARACIÓN Y PAGO BIMESTRAL'],
            ['codigo' => 109, 'nombre' => 'UTILIZADOS PARA ENVASAR, EMBALAR O EMPACAR'],
            ['codigo' => 110, 'nombre' => 'CORTE A 30 DE ABRIL'],
            ['codigo' => 111, 'nombre' => 'CORTE A 30 DE AGOSTO'],
            ['codigo' => 112, 'nombre' => 'CORTE A 31 DE DICIEMBRE'],
            ['codigo' => 113, 'nombre' => 'INGRESOS 68.015 y retenedores de ica $0'],
            ['codigo' => 114, 'nombre' => 'AÑO 2023'],
            ['codigo' => 115, 'nombre' => 'AÑO 2024'],
            ['codigo' => 116, 'nombre' => 'PAGO PRIMER TRIMESTRE'],
            ['codigo' => 117, 'nombre' => 'PAGO SEGUNDO TRIMESTRE'],
            ['codigo' => 118, 'nombre' => 'PAGO TERCER TRIMESTRE'],
            ['codigo' => 119, 'nombre' => 'PAGO CUARTO TRIMESTRE'],
            ['codigo' => 120, 'nombre' => 'DECLARACIÓN ANUAL'],
            ['codigo' => 121, 'nombre' => 'ENERO FEBRERO MARZO'],
            ['codigo' => 122, 'nombre' => 'ABRIL MAYO JUNIO'],
            ['codigo' => 123, 'nombre' => 'JULIO AGOSTO SEPTIEMBRE'],
            ['codigo' => 124, 'nombre' => 'OCTUBRE NOV DICIEMBRE'],
            ['codigo' => 125, 'nombre' => 'ENERO'],
            ['codigo' => 126, 'nombre' => 'FEBRERO'],
            ['codigo' => 127, 'nombre' => 'MARZO'],
            ['codigo' => 128, 'nombre' => 'ABRIL'],
            ['codigo' => 129, 'nombre' => 'MAYO'],
            ['codigo' => 130, 'nombre' => 'JUNIO'],
            ['codigo' => 131, 'nombre' => 'JULIO'],
            ['codigo' => 132, 'nombre' => 'AGOSTO'],
            ['codigo' => 133, 'nombre' => 'SEPTIEMBRE'],
            ['codigo' => 134, 'nombre' => 'OCTUBRE'],
            ['codigo' => 135, 'nombre' => 'NOVIEMBRE'],
            ['codigo' => 136, 'nombre' => 'DICIEMBRE'],
            ['codigo' => 137, 'nombre' => 'ICA ANUAL Y 1A CUOTA'],
            ['codigo' => 138, 'nombre' => '2 CUOTA ICA ANUAL'],
            ['codigo' => 139, 'nombre' => '3 CUOTA ICA ANUAL'],
            ['codigo' => 140, 'nombre' => '4 CUOTA ICA ANUAL'],
            ['codigo' => 141, 'nombre' => 'PRIMERA DECADA'],
            ['codigo' => 142, 'nombre' => 'SEGUNDA DECADA'],
            ['codigo' => 143, 'nombre' => 'TERCERA DECADA'],
            ['codigo' => 144, 'nombre' => 'MENSUAL FECHA 25 DE CADA MES'],
            ['codigo' => 145, 'nombre' => 'MENSUAL FECHA 30 DE CADA MES'],
            ['codigo' => 146, 'nombre' => 'NÓMINA QUINCENAL'],
            ['codigo' => 147, 'nombre' => 'DECLARACIÓN INICIAL'],
            ['codigo' => 148, 'nombre' => 'PRIMERA CUOTA'],
            ['codigo' => 149, 'nombre' => 'SEGUNDA CUOTA'],
            ['codigo' => 150, 'nombre' => 'TERCERA CUOTA'],
            ['codigo' => 151, 'nombre' => 'CUARTA CUOTA'],
            ['codigo' => 152, 'nombre' => 'PRIMER SEMESTRE'],
            ['codigo' => 153, 'nombre' => 'SEGUNDO SEMESTRE'],
            ['codigo' => 154, 'nombre' => 'INFORME PAÍS POR PAÍS'],
            ['codigo' => 155, 'nombre' => 'DEL 1 DE NOVIEMBRE AL 15 DE DICIEMBRE DE 2025'],
            ['codigo' => 156, 'nombre' => 'DEL 16 AL 31 DE DICIEMBRE DE 2025'],
            ['codigo' => 157, 'nombre' => 'CERTIFICADO ANUAL'],
            ['codigo' => 158, 'nombre' => 'AÑO 2023 y 2024']
        ];
        DetalleTributarioCT::insert($impuestos);
    }
}
