<?php

namespace Database\Seeders;

use App\Models\ObligacionesMunicipalesDian;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ObligacionesMunicipalesDianTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $impuestos = [
            ['codigo' => 999, 'nombre' => 'NO APLICA'],
            ['codigo' => 100, 'nombre' => 'ICA ANUAL MEDELLIN'],
            ['codigo' => 101, 'nombre' => 'ICA BIMESTRAL MEDELLIN'],
            ['codigo' => 102, 'nombre' => 'RETEICA BIMESTRAL MEDELLIN'],
            ['codigo' => 103, 'nombre' => 'ICA BIMESTRAL MEDELLIN - autoretenedores'],
            ['codigo' => 104, 'nombre' => 'ICA ANUAL PEREIRA'],
            ['codigo' => 105, 'nombre' => 'AUTORETEICA TRIMESTRAL PEREIRA'],
            ['codigo' => 106, 'nombre' => 'RETEICA BIMESTRAL PEREIRA'],
            ['codigo' => 107, 'nombre' => 'ICA BIMESTRAL RÉGIMEN SIMPLIFICADO ESPECIAL PEREIRA'],
            ['codigo' => 108, 'nombre' => 'ICA ANUAL VIRGINIA'],
            ['codigo' => 109, 'nombre' => 'RETEICA BIMESTRAL ENVIGADO'],
            ['codigo' => 110, 'nombre' => 'ICA ANUAL ENVIGADO'],
            ['codigo' => 111, 'nombre' => 'ICA BIMESTRAL ENVIGADO '],
            ['codigo' => 112, 'nombre' => 'RETEICA Y AUTORETENEDORES BIMESTRAL BELLO'],
            ['codigo' => 113, 'nombre' => 'ICA ANUAL BELLO'],
            ['codigo' => 114, 'nombre' => 'RETEICA MENSUAL COPACABANA'],
            ['codigo' => 115, 'nombre' => 'ICA ANUAL COPACABANA'],
            ['codigo' => 116, 'nombre' => 'ICA ANUAL LA ESTRELLA'],
            ['codigo' => 117, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL LA ESTRELLA'],
            ['codigo' => 118, 'nombre' => 'RETEICA Y AUTORETENEDORES BIMESTRAL AMAGÁ'],
            ['codigo' => 119, 'nombre' => 'ICA ANUAL AMAGÁ'],
            ['codigo' => 120, 'nombre' => 'ICA BIMESTRAL BOGOTA'],
            ['codigo' => 121, 'nombre' => 'RETEICA BIMESTRAL BOGOTA'],
            ['codigo' => 122, 'nombre' => 'ICA ANUAL BOGOTA'],
            ['codigo' => 123, 'nombre' => 'ICA ANUAL ARMENIA'],
            ['codigo' => 124, 'nombre' => 'ICA ANUAL ITAGUI'],
            ['codigo' => 125, 'nombre' => 'ICA ANUAL SABANETA'],
            ['codigo' => 126, 'nombre' => 'ICA ANUAL BARRANQUILLA'],
            ['codigo' => 127, 'nombre' => 'ICA ANUAL CALI -INGRESOS MAYORES A 131.952 UVT'],
            ['codigo' => 128, 'nombre' => 'ICA ANUAL BARRANCABERMEJA'],
            ['codigo' => 129, 'nombre' => 'ICA ANUAL BUCARAMANGA'],
            ['codigo' => 130, 'nombre' => 'ICA ANUAL RIONEGRO'],
            ['codigo' => 131, 'nombre' => 'ICA ANUAL BARBOSA ANTIOQUIA'],
            ['codigo' => 132, 'nombre' => 'ICA ANUAL GIRARDOTA'],
            ['codigo' => 133, 'nombre' => 'ICA BIMESTRAL BARBOSA ANTIOQUIA'],
            ['codigo' => 134, 'nombre' => 'ICA BIMESTRAL CALI'],
            ['codigo' => 135, 'nombre' => 'ICA BIMESTRAL BARRANQUILLA - NO APLICA 2025'],
            ['codigo' => 136, 'nombre' => 'ICA ANUAL VALLEDUPAR '],
            ['codigo' => 137, 'nombre' => 'RETEICA BIMESTRAL VALLEDUPAR'],
            ['codigo' => 138, 'nombre' => 'ICA ANUAL EL SANTUARIO '],
            ['codigo' => 139, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL EL SANTUARIO'],
            ['codigo' => 140, 'nombre' => 'ICA ANUAL COTA'],
            ['codigo' => 141, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL COTA'],
            ['codigo' => 142, 'nombre' => 'ICA ANUAL DOSQUEBRADAS'],
            ['codigo' => 143, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL DOSQUEBRADAS'],
            ['codigo' => 144, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES BARRANQUILLA'],
            ['codigo' => 145, 'nombre' => 'ICA BIMESTRAL BARRANQUILLA - REGIMEN ESPECIAL'],
            ['codigo' => 146, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL BUCARAMANGA'],
            ['codigo' => 147, 'nombre' => 'ICA ANUAL CALI - INGRESOS MAYORES A 32.998 UVT Y MENOR A 131.952 UVT'],
            ['codigo' => 148, 'nombre' => 'ICA ANUAL CALI - INGRESOS MENORES A 32.998 UVT'],
            ['codigo' => 149, 'nombre' => 'RETENCIÓN Y AUTORETENCIÓN ICA BIMESTRAL CALI'],
            ['codigo' => 150, 'nombre' => 'RETEICA MENSUAL YUMBO'],
            ['codigo' => 151, 'nombre' => 'ICA ANUAL YUMBO'],
            ['codigo' => 152, 'nombre' => 'RETENCIÓN ICA BIMESTRAL BARRANCAS'],
            ['codigo' => 153, 'nombre' => 'AUTORETENCIÓN ICA MENSUAL BARRANCAS'],
            ['codigo' => 154, 'nombre' => 'ICA ANUAL BARRANCAS'],
            ['codigo' => 155, 'nombre' => 'EXÓGENA MUNICIPAL BARRANCAS'],
            ['codigo' => 156, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL ITAGUI'],
            ['codigo' => 157, 'nombre' => 'ICA ANUAL PUERTO ASIS'],
            ['codigo' => 158, 'nombre' => 'ICA ANUAL GACHANCIPÁ'],
            ['codigo' => 159, 'nombre' => 'ICA ANUAL PUERTO GAITÁN'],
            ['codigo' => 160, 'nombre' => 'RETEICA BIMESTRAL PUERTO GAITÁN'],
            ['codigo' => 161, 'nombre' => 'EXÓGENA MUNICIPAL BARRANQUILLA'],
            ['codigo' => 162, 'nombre' => 'EXÓGENA MUNICIPAL BELLO'],
            ['codigo' => 163, 'nombre' => 'EXÓGENA MUNICIPAL BOGOTÁ'],
            ['codigo' => 164, 'nombre' => 'EXÓGENA MUNICIPAL BUCARAMANGA'],
            ['codigo' => 165, 'nombre' => 'EXÓGENA MUNICIPAL BUENAVENTURA'],
            ['codigo' => 166, 'nombre' => 'ICA ANUAL BUENAVENTURA'],
            ['codigo' => 167, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL BUENAVENTURA'],
            ['codigo' => 168, 'nombre' => 'ICA ANUAL CARTAGENA'],
            ['codigo' => 169, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CARTAGENA'],
            ['codigo' => 170, 'nombre' => 'EXÓGENA MUNICIPAL CARTAGENA'],
            ['codigo' => 171, 'nombre' => 'ICA ANUAL CIÉNAGA'],
            ['codigo' => 172, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CIÉNAGA'],
            ['codigo' => 173, 'nombre' => 'EXÓGENA MUNICIPAL CIÉNAGA'],
            ['codigo' => 174, 'nombre' => 'ICA ANUAL DIBULLA'],
            ['codigo' => 175, 'nombre' => 'ICA Y RETEICA BIMESTRAL DIBULLA'],
            ['codigo' => 176, 'nombre' => 'ICA ANUAL JAMUNDI'],
            ['codigo' => 177, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL JAMUNDI'],
            ['codigo' => 178, 'nombre' => 'EXÓGENA MUNICIPAL MEDELLIN'],
            ['codigo' => 179, 'nombre' => 'ICA ANUAL SANTA MARTA'],
            ['codigo' => 180, 'nombre' => 'AUTORETEICA BIMESTRAL SANTA MARTA'],
            ['codigo' => 181, 'nombre' => 'RETEICA MENSUAL SANTA MARTA'],
            ['codigo' => 182, 'nombre' => 'ICA ANUAL SANTANDER DE QUILICHAO'],
            ['codigo' => 183, 'nombre' => 'RETEICA BIMESTRAL SANTANDER DE QUILICHAO'],
            ['codigo' => 184, 'nombre' => 'ICA ANUAL TULUA'],
            ['codigo' => 185, 'nombre' => 'ICA BIMESTRAL TULUA'],
            ['codigo' => 186, 'nombre' => 'RETEICA BIMESTRAL TULUA'],
            ['codigo' => 187, 'nombre' => 'ICA ANUAL URIBIA'],
            ['codigo' => 188, 'nombre' => 'RETEICA BIMESTRAL URIBIA'],
            ['codigo' => 189, 'nombre' => 'EXÓGENA MUNICIPAL URIBIA'],
            ['codigo' => 190, 'nombre' => 'EXÓGENA MUNICIPAL YUMBO'],
            ['codigo' => 191, 'nombre' => 'EXÓGENA MUNICIPAL PEREIRA'],
            ['codigo' => 192, 'nombre' => 'EXÓGENA MUNICIPAL DOSQUEBBRADAS'],
            ['codigo' => 193, 'nombre' => 'EXÓGENA MUNICIPAL CALI'],
            ['codigo' => 194, 'nombre' => 'EXÓGENA MUNICIPAL COTA'],
            ['codigo' => 195, 'nombre' => 'RETEICA Y AUTORETEICA BIMENSUAL REGIMEN COMÚN BARRANQUILLA'],
            ['codigo' => 196, 'nombre' => 'RETEICA MENSUAL PALMIRA'],
            ['codigo' => 197, 'nombre' => 'ICA ANUAL PALMIRA'],
            ['codigo' => 198, 'nombre' => 'EXÓGENA MUNICIPAL PALMIRA'],
            ['codigo' => 199, 'nombre' => 'RETEICA BIMESTRAL PASTO'],
            ['codigo' => 200, 'nombre' => 'EXÓGENA MUNICIPAL PASTO'],
            ['codigo' => 201, 'nombre' => 'ICA ANUAL PASTO'],
            ['codigo' => 202, 'nombre' => 'RETEICA MENSUAL POPAYÁN'],
            ['codigo' => 203, 'nombre' => 'ICA ANUAL POPAYÁN'],
            ['codigo' => 204, 'nombre' => 'ICA ANUAL YOPAL'],
            ['codigo' => 205, 'nombre' => 'RETEICA BIMESTRAL YOPAL'],
            ['codigo' => 206, 'nombre' => 'ICA BIMESTRAL YOPAL'],
            ['codigo' => 207, 'nombre' => 'EXÓGENA MUNICIPAL YOPAL'],
            ['codigo' => 208, 'nombre' => 'ICA ANUAL VIJES'],
            ['codigo' => 209, 'nombre' => 'RETEICA BIMESTRAL VIJES'],
            ['codigo' => 210, 'nombre' => 'AUTO RETEICA BIMESTRAL VIJES'],
            ['codigo' => 211, 'nombre' => 'ICA ANUAL BUGA'],
            ['codigo' => 212, 'nombre' => 'AUTORETEICA Y RETEICA MENSUAL BUGA'],
            ['codigo' => 213, 'nombre' => 'ICA ANUAL EL CERRITO'],
            ['codigo' => 214, 'nombre' => 'EXÓGENA MUNICIPALEL CERRITO'],
            ['codigo' => 215, 'nombre' => 'AUTORETEICA Y RETEICA BIMESTRAL EL CERRITO'],
            ['codigo' => 216, 'nombre' => 'ICA ANUAL GINEBRA'],
            ['codigo' => 217, 'nombre' => 'RETEICA MENSUAL GINEBRA'],
            ['codigo' => 218, 'nombre' => 'ICA ANUAL GUACARÍ'],
            ['codigo' => 219, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL GUACARÍ'],
            ['codigo' => 220, 'nombre' => 'EXÓGENA MUNICIPAL GUACARÍ'],
            ['codigo' => 221, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL ARMENIA'],
            ['codigo' => 222, 'nombre' => 'EXÓGENA MUNICIPAL ARMENIA'],
            ['codigo' => 223, 'nombre' => 'ICA ANUAL MANIZALES'],
            ['codigo' => 224, 'nombre' => 'RETEICA BIMESTRAL MANIZALES'],
            ['codigo' => 225, 'nombre' => 'AUTO RETEICA BIMESTRAL MANIZALES'],
            ['codigo' => 226, 'nombre' => 'EXÓGENA MUNICIPAL MANIZALES'],
            ['codigo' => 227, 'nombre' => 'ICA ANUAL JERICÓ'],
            ['codigo' => 228, 'nombre' => 'RETEICA BIMESTRAL JERICÓ'],
            ['codigo' => 229, 'nombre' => 'ICA ANUAL QUIMBAYA'],
            ['codigo' => 230, 'nombre' => 'ICA ANUAL PUERTO ASIS'],
            ['codigo' => 231, 'nombre' => 'ICA ANUAL CIUDAD BOLÍVAR'],
            ['codigo' => 232, 'nombre' => 'RETEICA BIMESTRAL CIUDAD BOLÍVAR'],
            ['codigo' => 233, 'nombre' => 'AUTO RETEICA BIMESTRAL CIUDAD BOLÍVAR'],
            ['codigo' => 234, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SANTA BÁRBARA'],
            ['codigo' => 235, 'nombre' => 'ICA MENSUAL SANTA BÁRBARA'],
            ['codigo' => 236, 'nombre' => 'ICA ANUAL SANTA BÁRBARA'],
            ['codigo' => 237, 'nombre' => 'ICA ANUAL CIRCASIA'],
            ['codigo' => 238, 'nombre' => 'AUTO RETEICA BIMESTRAL CIRCASIA'],
            ['codigo' => 239, 'nombre' => 'RETEICA BIMESTRAL CIRCASIA'],
            ['codigo' => 240, 'nombre' => 'EXÓGENA MUNICIPAL CIRCASIA'],
            ['codigo' => 241, 'nombre' => 'RETEICA MENSUAL PUERTO ASIS'],
            ['codigo' => 242, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL VALLEDUPAR'],
            ['codigo' => 243, 'nombre' => 'AUTO RETEICA BIMESTRAL COPACABANA'],
            ['codigo' => 244, 'nombre' => 'RETEICA BIMESTRAL COPACABANA'],
            ['codigo' => 245, 'nombre' => 'EXÓGENA MUNICIPAL COPACABANA'],
            ['codigo' => 246, 'nombre' => 'AUTORETEICA BIMESTRAL URIBIA'],
            ['codigo' => 247, 'nombre' => 'ICA ANUAL VILLAVICENCIO EMPRESAS'],
            ['codigo' => 248, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL VILLAVICENCIO'],
            ['codigo' => 249, 'nombre' => 'EXÓGENA MUNICIPAL VILLAVICENCIO'],
            ['codigo' => 250, 'nombre' => 'ICA ANUAL CHÍA'],
            ['codigo' => 251, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CHÍA'],
            ['codigo' => 252, 'nombre' => 'EXÓGENA MUNICIPAL CHÍA'],
            ['codigo' => 253, 'nombre' => 'RETEICA BIMESTRAL ZIPAQUIRÁ'],
            ['codigo' => 254, 'nombre' => 'ICA ANUAL ZIPAQUIRÁ'],
            ['codigo' => 255, 'nombre' => 'ICA ANUAL APARTADÓ'],
            ['codigo' => 256, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL APARTADÓ'],
            ['codigo' => 257, 'nombre' => 'ICA ANUAL NEIVA'],
            ['codigo' => 258, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL NEIVA'],
            ['codigo' => 259, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL NEIVA - AGENTES AUTORETENEDORES'],
            ['codigo' => 260, 'nombre' => 'EXÓGENA MUNICIPAL NEIVA'],
            ['codigo' => 261, 'nombre' => 'ICA ANUAL SAN ANDRÉS'],
            ['codigo' => 262, 'nombre' => 'ICA ANUAL CÚCUTA'],
            ['codigo' => 263, 'nombre' => 'RETEICA Y AUTO RETEICA BIMESTRAL CÚCUTA'],
            ['codigo' => 264, 'nombre' => 'ICA BIMESTRAL ENTIDADES FINANCIERAS CÚCUTA'],
            ['codigo' => 265, 'nombre' => 'ICA ANUAL IBAGUÉ'],
            ['codigo' => 266, 'nombre' => 'RETEICA BIMESTRAL IBAGUÉ'],
            ['codigo' => 267, 'nombre' => 'EXÓGENA MUNICIPAL MONTERÍA'],
            ['codigo' => 268, 'nombre' => 'ICA ANUAL MONTERÍA'],
            ['codigo' => 269, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL MONTERÍA'],
            ['codigo' => 270, 'nombre' => 'EXÓGENA MUNICIPAL RIONEGRO'],
            ['codigo' => 271, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL RIONEGRO'],
            ['codigo' => 272, 'nombre' => 'ICA ANUAL EL RETIRO'],
            ['codigo' => 273, 'nombre' => 'EXÓGENA MUNICIPAL EL RETIRO'],
            ['codigo' => 274, 'nombre' => 'RETEICA BIMESTRAL EL RETIRO'],
            ['codigo' => 275, 'nombre' => 'ICA MENSUAL EL RETIRO'],
            ['codigo' => 276, 'nombre' => 'IMPUESTO PREDIAL BOGOTÁ - PAGO ALTERNATIVO POR CUOTAS'],
            ['codigo' => 277, 'nombre' => 'EXÓGENA MUNICIPAL BARBOSA ANTIOQUIA'],
            ['codigo' => 278, 'nombre' => 'AUTORETEICA BIMESTRAL BARBOSA ANTIOQUIA'],
            ['codigo' => 279, 'nombre' => 'EXÓGENA MUNICIPAL GIRARDOT'],
            ['codigo' => 280, 'nombre' => 'RETEICA MENSUAL GIRARDOT'],
            ['codigo' => 281, 'nombre' => 'ICA ANUAL GIRARDOT'],
            ['codigo' => 282, 'nombre' => 'ICA ANUAL EL BAGRE'],
            ['codigo' => 283, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL EL BAGRE'],
            ['codigo' => 284, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL CHIGORODÓ'],
            ['codigo' => 285, 'nombre' => 'ICA ANUAL CHIGORODÓ'],
            ['codigo' => 286, 'nombre' => 'ICA ANUAL FREDONIA'],
            ['codigo' => 287, 'nombre' => 'ICA MENSUAL FREDONIA'],
            ['codigo' => 288, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL FREDONIA'],
            ['codigo' => 289, 'nombre' => 'EXÓGENA MUNICIPAL FREDONIA'],
            ['codigo' => 290, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL GIRARDOTA'],
            ['codigo' => 291, 'nombre' => 'INACTIVO'],
            ['codigo' => 292, 'nombre' => 'EXÓGENA MUNICIPAL GIRARDOTA'],
            ['codigo' => 293, 'nombre' => 'ICA MENSUAL GUARNE'],
            ['codigo' => 294, 'nombre' => 'ICA ANUAL GUARNE'],
            ['codigo' => 295, 'nombre' => 'RETEICA BIMESTRAL GUARNE'],
            ['codigo' => 296, 'nombre' => 'AUTORETEICA BIMESTRAL GUARNE'],
            ['codigo' => 297, 'nombre' => 'ICA MENSUAL YARUMAL'],
            ['codigo' => 298, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL YARUMAL'],
            ['codigo' => 299, 'nombre' => 'ICA ANUAL YARUMAL'],
            ['codigo' => 300, 'nombre' => 'ICA ANUAL SONSON'],
            ['codigo' => 301, 'nombre' => 'RETEICA BIMESTRAL SONSON'],
            ['codigo' => 302, 'nombre' => 'AUTORETEICA BIMESTRAL SONSON'],
            ['codigo' => 303, 'nombre' => 'EXÓGENA MUNICIPAL SONSON'],
            ['codigo' => 304, 'nombre' => 'ICA ANUAL PUERTO BERRIO'],
            ['codigo' => 305, 'nombre' => 'RETEICA BIMESTRAL PUERTO BERRIO'],
            ['codigo' => 306, 'nombre' => 'EXÓGENA MUNICIPAL PUERTO BERRIO'],
            ['codigo' => 307, 'nombre' => 'EXÓGENA MUNICIPAL NECOCLÍ'],
            ['codigo' => 308, 'nombre' => 'RETEICA BIMESTRAL NECOCLÍ'],
            ['codigo' => 309, 'nombre' => 'ICA ANUAL NECOCLÍ'],
            ['codigo' => 310, 'nombre' => 'ICA ANUAL MARINILLA'],
            ['codigo' => 311, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL MARINILLA'],
            ['codigo' => 312, 'nombre' => 'EXÓGENA MUNICIPAL MARINILLA'],
            ['codigo' => 313, 'nombre' => 'RETEICA BIMESTRAL LA CEJA'],
            ['codigo' => 314, 'nombre' => 'ICA ANUAL LA CEJA'],
            ['codigo' => 315, 'nombre' => 'ICA ANUAL GUATAPÉ'],
            ['codigo' => 316, 'nombre' => 'RETEICA BIMESTRAL GUATAPÉ'],
            ['codigo' => 317, 'nombre' => 'ICA ANUAL CAUCASIA'],
            ['codigo' => 318, 'nombre' => 'RETEICA BIMESTRAL CAUCASIA'],
            ['codigo' => 319, 'nombre' => 'EXÓGENA MUNICIPAL CAUCASIA'],
            ['codigo' => 320, 'nombre' => 'ICA ANUAL CAÑAS GORDAS'],
            ['codigo' => 321, 'nombre' => 'RETEICA BIMESTRAL CAÑAS GORDAS'],
            ['codigo' => 322, 'nombre' => 'AUTORETEICA BIMESTRAL CAÑAS GORDAS'],
            ['codigo' => 323, 'nombre' => 'ICA ANUAL TAME'],
            ['codigo' => 324, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL TAME'],
            ['codigo' => 325, 'nombre' => 'ICA ANUAL SOLEDAD'],
            ['codigo' => 326, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SOLEDAD'],
            ['codigo' => 327, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES SOLEDAD'],
            ['codigo' => 328, 'nombre' => 'EXÓGENA MUNICIPAL SOLEDAD'],
            ['codigo' => 329, 'nombre' => 'ICA ANUAL CHINCHINÁ'],
            ['codigo' => 330, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CHINCHINÁ'],
            ['codigo' => 331, 'nombre' => 'ICA ANUAL VILLANUEVA CASANARE'],
            ['codigo' => 332, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL VILLANUEVA CASANARE'],
            ['codigo' => 333, 'nombre' => 'EXÓGENA MUNICIPAL VILLANUEVA CASANARE'],
            ['codigo' => 334, 'nombre' => 'ICA ANUAL INZA'],
            ['codigo' => 335, 'nombre' => 'RETEICA MENSUAL INZA'],
            ['codigo' => 336, 'nombre' => 'ICA ANUAL PERSONAS SAN MARTÍN CESAR'],
            ['codigo' => 337, 'nombre' => 'ICA ANUAL EMPRESAS SAN MARTÍN CESAR'],
            ['codigo' => 338, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SAN MARTÍN CESAR'],
            ['codigo' => 339, 'nombre' => 'EXÓGENA MUNICIPAL SAN MARTÍN CESAR'],
            ['codigo' => 340, 'nombre' => 'ICA ANUAL CONDOTO'],
            ['codigo' => 341, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL CONDOTO'],
            ['codigo' => 342, 'nombre' => 'ICA ANUAL SAHAGÚN'],
            ['codigo' => 343, 'nombre' => 'RETEICA BIMESTRAL SAHAGÚN'],
            ['codigo' => 344, 'nombre' => 'ICA ANUAL PUERTO LIBERTADOR'],
            ['codigo' => 345, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL PUERTO LIBERTADOR'],
            ['codigo' => 346, 'nombre' => 'ICA MENSUAL GRANDES CONTRIBUYENTES SINCELEJO'],
            ['codigo' => 347, 'nombre' => 'ICA BIMESTRAL SINCELEJO'],
            ['codigo' => 348, 'nombre' => 'ICA ANUAL SINCELEJO'],
            ['codigo' => 349, 'nombre' => 'ICA ANUAL LA JAGUA DE IBIRICO'],
            ['codigo' => 350, 'nombre' => 'RETEICA BIMESTRAL LA JAGUA DE IBIRICO'],
            ['codigo' => 351, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES LA JAGUA DE IBIRICO'],
            ['codigo' => 352, 'nombre' => 'EXÓGENA MUNICIPAL LA JAGUA DE IBIRICO'],
            ['codigo' => 353, 'nombre' => 'ICA ANUAL BECERRIL'],
            ['codigo' => 354, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES BECERRIL'],
            ['codigo' => 355, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL BECERRIL'],
            ['codigo' => 356, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SERVICIOS FINANCIEROS BECERRIL'],
            ['codigo' => 357, 'nombre' => 'EXÓGENA MUNICIPAL BECERRIL'],
            ['codigo' => 358, 'nombre' => 'ICA ANUAL SAN CAYETANO - CUNDINAMARCA'],
            ['codigo' => 359, 'nombre' => 'RETEICA MENSUAL SAN CAYETANO  - CUNDINAMARCA'],
            ['codigo' => 360, 'nombre' => 'EXÓGENA MUNICIPAL SAN CAYETANO  - CUNDINAMARCA'],
            ['codigo' => 361, 'nombre' => 'ICA ANUAL TURBANÁ'],
            ['codigo' => 362, 'nombre' => 'ICA ANUAL CAJAMARCA'],
            ['codigo' => 363, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CAJAMARCA'],
            ['codigo' => 364, 'nombre' => 'EXÓGENA MUNICIPAL CAJAMARCA'],
            ['codigo' => 365, 'nombre' => 'ICA ANUAL PUERTO LÓPEZ'],
            ['codigo' => 366, 'nombre' => 'RETEICA MENSUAL PUERTO LÓPEZ'],
            ['codigo' => 367, 'nombre' => 'ICA ANUAL PERSONAS SOPÓ'],
            ['codigo' => 368, 'nombre' => 'ICA ANUAL EMPRESAS SOPÓ'],
            ['codigo' => 369, 'nombre' => 'RETEICA MENSUAL SOPÓ'],
            ['codigo' => 370, 'nombre' => 'AUTORETEICA BIMESTRAL SOPÓ'],
            ['codigo' => 371, 'nombre' => 'ICA ANUAL LA PINTADA'],
            ['codigo' => 372, 'nombre' => 'RETEICA BIMESTRAL LA PINTADA'],
            ['codigo' => 373, 'nombre' => 'EXÓGENA MUNICIPAL GRANDES CONTRIUYENTES LA PINTADA'],
            ['codigo' => 374, 'nombre' => 'EXÓGENA MUNICIPAL EMPRESAS Y PERSONAS LA PINTADA'],
            ['codigo' => 375, 'nombre' => 'RETEICA BIMESTRAL ROLDANILLO'],
            ['codigo' => 376, 'nombre' => 'ICA ANUAL ROLDANILLO'],
            ['codigo' => 377, 'nombre' => 'ICA ANUAL PUERTO TEJADA'],
            ['codigo' => 378, 'nombre' => 'RETEICA MENSUAL PUERTO TEJADA'],
            ['codigo' => 379, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL GALAPA'],
            ['codigo' => 380, 'nombre' => 'ICA ANUAL GALAPA'],
            ['codigo' => 381, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES GALAPA'],
            ['codigo' => 382, 'nombre' => 'EXÓGENA MUNICIPAL GALAPA'],
            ['codigo' => 383, 'nombre' => 'ICA ANUAL OCAÑA'],
            ['codigo' => 384, 'nombre' => 'AUTORETEICA BIMESTRAL LA PINTADA'],
            ['codigo' => 385, 'nombre' => 'ICA ANUAL CARMEN DE VIBORAL'],
            ['codigo' => 386, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CARMEN DE VIBORAL'],
            ['codigo' => 387, 'nombre' => 'EXÓGENA MUNICIPAL CARMEN DE VIBORAL'],
            ['codigo' => 388, 'nombre' => 'EXÓGENA MUNICIPAL ITAGUI'],
            ['codigo' => 389, 'nombre' => 'AUTORETEICA MENSUAL APARTADÓ'],
            ['codigo' => 390, 'nombre' => 'EXÓGENA MUNICIPAL APARTADÓ'],
            ['codigo' => 391, 'nombre' => 'AUTORETEICA BIMESTRAL ENVIGADO'],
            ['codigo' => 392, 'nombre' => 'EXÓGENA MUNICIPAL ENVIGADO'],
            ['codigo' => 393, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SABANETA'],
            ['codigo' => 394, 'nombre' => 'EXÓGENA MUNICIPAL SABANETA'],
            ['codigo' => 395, 'nombre' => 'EXÓGENA MUNICIPAL YARUMAL'],
            ['codigo' => 396, 'nombre' => 'ICA ANUAL SAN JERÓNIMO'],
            ['codigo' => 397, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SAN JERÓNIMO'],
            ['codigo' => 398, 'nombre' => 'EXÓGENA MUNICIPAL LA ESTRELLA'],
            ['codigo' => 399, 'nombre' => 'AUTORETEICA BIMESTRAL LA CEJA'],
            ['codigo' => 400, 'nombre' => 'EXÓGENA MUNICIPAL GUATAPÉ'],
            ['codigo' => 401, 'nombre' => 'EXÓGENA MUNICIPAL CHIGORODÓ'],
            ['codigo' => 402, 'nombre' => 'ICA ANUAL PUERTO COLOMBIA'],
            ['codigo' => 403, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL PUERTO COLOMBIA'],
            ['codigo' => 404, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES PUERTO COLOMBIA'],
            ['codigo' => 405, 'nombre' => 'ICA ANUAL TUNJA'],
            ['codigo' => 406, 'nombre' => 'ICA BIMESTRAL TUNJA'],
            ['codigo' => 407, 'nombre' => 'RETEICA MENSUAL TUNJA'],
            ['codigo' => 408, 'nombre' => 'EXÓGENA MUNICIPAL GRANDES CONTRIUYENTES TUNJA'],
            ['codigo' => 409, 'nombre' => 'EXÓGENA MUNICIPAL PERSONAS Y EMPRESAS TUNJA'],
            ['codigo' => 410, 'nombre' => 'ICA ANUAL FLORENCIA'],
            ['codigo' => 484, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL FLORENCIA'],
            ['codigo' => 412, 'nombre' => 'ICA ANUAL SUPÍA'],
            ['codigo' => 413, 'nombre' => 'RETEICA BIMESTRAL SUPÍA'],
            ['codigo' => 414, 'nombre' => 'ICA ANUAL QUIBDÓ'],
            ['codigo' => 415, 'nombre' => 'RETEICA BIMESTRAL QUIBDÓ'],
            ['codigo' => 416, 'nombre' => 'EXÓGENA MUNICIPAL QUIBDÓ'],
            ['codigo' => 417, 'nombre' => 'ICA ANUAL AGUA DE DIOS'],
            ['codigo' => 418, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL AGUA DE DIOS'],
            ['codigo' => 419, 'nombre' => 'ICA ANUAL SOACHA'],
            ['codigo' => 420, 'nombre' => 'AUTORETEICA BIMESTRAL SOACHA'],
            ['codigo' => 421, 'nombre' => 'RETEICA MENSUAL SOACHA'],
            ['codigo' => 423, 'nombre' => 'EXÓGENA MUNICIPAL GACHANCIPÁ'],
            ['codigo' => 424, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL GACHANCIPÁ'],
            ['codigo' => 425, 'nombre' => 'ICA ANUAL GACHANCIPÁ'],
            ['codigo' => 426, 'nombre' => 'EXÓGENA MUNICIPAL RIOHACHA'],
            ['codigo' => 427, 'nombre' => 'ICA ANUAL RIOHACHA'],
            ['codigo' => 428, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL - GRANDES CONTRIBUYENTES RIOHACHA'],
            ['codigo' => 429, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL - RÉGIMEN COMÚN RIOHACHA'],
            ['codigo' => 430, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GRANDES CONTRIBUYENTES CIÉNAGA'],
            ['codigo' => 431, 'nombre' => 'EXÓGENA MUNICIPAL BUGA'],
            ['codigo' => 432, 'nombre' => 'REPORTE DE TERCEROS RETENIDOS BIMESTRAL JAMUNDI'],
            ['codigo' => 433, 'nombre' => 'EXÓGENA MUNICIPAL JAMUNDI'],
            ['codigo' => 434, 'nombre' => 'EXÓGENA MUNICIPAL TULUA'],
            ['codigo' => 435, 'nombre' => 'EXÓGENA MUNICIPAL IBAGUÉ'],
            ['codigo' => 436, 'nombre' => 'EXÓGENA MUNICIPAL SINCELEJO'],
            ['codigo' => 437, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL BARRANCABERMEJA'],
            ['codigo' => 438, 'nombre' => 'ICA ANUAL FLORIDABLANCA'],
            ['codigo' => 439, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL FLORIDABLANCA'],
            ['codigo' => 440, 'nombre' => 'EXÓGENA MUNICIPAL FLORIDABLANCA'],
            ['codigo' => 441, 'nombre' => 'ICA ANUAL PERSONAS GIRÓN'],
            ['codigo' => 442, 'nombre' => 'ICA ANUAL EMPRESAS GIRÓN'],
            ['codigo' => 443, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL GIRÓN'],
            ['codigo' => 445, 'nombre' => 'ICA ANUAL LEBRIJA'],
            ['codigo' => 446, 'nombre' => 'AUTORETEICA BIMESTRAL LEBRIJA'],
            ['codigo' => 447, 'nombre' => 'RETEICA MENSUAL LEBRIJA'],
            ['codigo' => 448, 'nombre' => 'EXÓGENA MUNICIPAL LEBRIJA'],
            ['codigo' => 449, 'nombre' => 'ICA ANUAL ABRIAQUIL'],
            ['codigo' => 450, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL ABRIAQUIL'],
            ['codigo' => 451, 'nombre' => 'ICA MENSUAL RÉGIMEN COMÚN ABRIAQUIL'],
            ['codigo' => 452, 'nombre' => 'ICA ANUAL MUTATÁ'],
            ['codigo' => 453, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL MUTATÁ'],
            ['codigo' => 454, 'nombre' => 'RETEICA MENSUAL NECOCLÍ'],
            ['codigo' => 455, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL TURBANÁ'],
            ['codigo' => 456, 'nombre' => 'ICA ANUAL IPIALES'],
            ['codigo' => 457, 'nombre' => 'RETEICA BIMESTRAL IPIALES'],
            ['codigo' => 458, 'nombre' => 'EXÓGENA MUNICIPAL IPIALES'],
            ['codigo' => 459, 'nombre' => 'RETEICA BIMESTRAL OCAÑA'],
            ['codigo' => 460, 'nombre' => 'AUTORETEICA BIMESTRAL ZIPAQUIRÁ'],
            ['codigo' => 461, 'nombre' => 'ICA ANUAL VILLAVICENCIO PERSONAS'],
            ['codigo' => 462, 'nombre' => 'EXÓGENA MUNICIPAL PUERTO GAITÁN'],
            ['codigo' => 463, 'nombre' => 'ICA ANUAL MOCOA'],
            ['codigo' => 464, 'nombre' => 'RETEICA MENSUAL MOCOA'],
            ['codigo' => 465, 'nombre' => 'EXÓGENA MUNICIPAL MOCOA'],
            ['codigo' => 466, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CALDAS'],
            ['codigo' => 467, 'nombre' => 'ICA ANUAL CALDAS'],
            ['codigo' => 468, 'nombre' => 'ICA ANUAL URRAO'],
            ['codigo' => 469, 'nombre' => 'RETEICA BIMESTRAL URRAO'],
            ['codigo' => 470, 'nombre' => 'ICA MENSUAL URRAO'],
            ['codigo' => 483, 'nombre' => 'EXÓGENA MUNICIPAL AMAGÁ'],
            ['codigo' => 472, 'nombre' => 'ICA ANUAL PROVIDENCIA'],
            ['codigo' => 473, 'nombre' => 'RETEICA MENSUAL PROVIDENCIA'],
            ['codigo' => 474, 'nombre' => 'ICA ANUAL RÉGIMEN SIMPLIFICADO FACATATIVÁ'],
            ['codigo' => 475, 'nombre' => 'ICA ANUAL RÉGIMEN COMÚN FACATATIVÁ'],
            ['codigo' => 476, 'nombre' => 'AUTORETEICA BIMESTRAL FACATATIVÁ'],
            ['codigo' => 477, 'nombre' => 'RETEICA BIMESTRAL FACATATIVÁ'],
            ['codigo' => 478, 'nombre' => 'EXÓGENA MUNICIPAL FACATATIVÁ'],
            ['codigo' => 479, 'nombre' => 'ICA ANUAL TESALIA'],
            ['codigo' => 480, 'nombre' => 'RETEICA BIMESTRAL TESALIA'],
            ['codigo' => 485, 'nombre' => 'EXÓGENA MUNICIPAL TESALIA'],
            ['codigo' => 486, 'nombre' => 'ICA ANUAL PAICOL'],
            ['codigo' => 487, 'nombre' => 'RETEICA BIMESTRAL PAICOL'],
            ['codigo' => 488, 'nombre' => 'ICA ANUAL GIGANTE'],
            ['codigo' => 489, 'nombre' => 'RETEICA BIMESTRAL GIGANTE'],
            ['codigo' => 490, 'nombre' => 'ICA ANUAL SAN PEDRO DE LOS MILAGROS'],
            ['codigo' => 491, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SAN PEDRO DE LOS MILAGROS'],
            ['codigo' => 492, 'nombre' => 'EXÓGENA MUNICIPAL SAN PEDRO DE LOS MILAGROS'],
            ['codigo' => 493, 'nombre' => 'ICA ANUAL AGUAZUL PERSONAS'],
            ['codigo' => 494, 'nombre' => 'ICA ANUAL AGUAZUL EMPRESAS'],
            ['codigo' => 495, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL AGUAZUL'],
            ['codigo' => 496, 'nombre' => 'EXÓGENA MUNICIPAL AGUAZUL'],
            ['codigo' => 497, 'nombre' => 'EXÓGENA MUNICIPAL PERSONAS Y EMPRESAS - LA TEBAIDA'],
            ['codigo' => 498, 'nombre' => 'EXÓGENA MUNICIPAL - GRANDES CONTRIBUYENTES LA TEBAIDA'],
            ['codigo' => 499, 'nombre' => 'RETEICA BIMESTRAL LA TEBAIDA'],
            ['codigo' => 500, 'nombre' => 'AUTORETEICA BIMESTRAL LA TEBAIDA'],
            ['codigo' => 501, 'nombre' => 'ICA ANUAL LA TEBAIDA'],
            ['codigo' => 502, 'nombre' => 'ICA ANUAL ACACÍAS'],
            ['codigo' => 503, 'nombre' => 'RETEICA BIMESTRAL ACACÍAS'],
            ['codigo' => 504, 'nombre' => 'ICA ANUAL CANDELARIA'],
            ['codigo' => 505, 'nombre' => 'RETEICA BIMESTRAL CANDELARIA'],
            ['codigo' => 506, 'nombre' => 'ICA ANUAL COVEÑAS'],
            ['codigo' => 507, 'nombre' => 'RETEICA BIMESTRAL COVEÑAS'],
            ['codigo' => 508, 'nombre' => 'EXOGENA MUNICIPAL COVEÑAS'],
            ['codigo' => 509, 'nombre' => 'ICA ANUAL GRANADA'],
            ['codigo' => 511, 'nombre' => 'EXOGENA MUNICIPAL GRANADA'],
            ['codigo' => 512, 'nombre' => 'RETEICA BIMESTRAL JARDÍN'],
            ['codigo' => 513, 'nombre' => 'EXOGENA MUNICIPAL JARDÍN'],
            ['codigo' => 514, 'nombre' => 'ICA ANUAL JARDÍN'],
            ['codigo' => 515, 'nombre' => 'ICA ANUAL RÉGIMEN COMÚN PUERTO TRIUNFO'],
            ['codigo' => 516, 'nombre' => 'ICA ANUAL RÉGIMEN SIMPLIFICADO PUERTO TRIUNFO'],
            ['codigo' => 517, 'nombre' => 'RETEICA BIMESTRAL PUERTO TRIUNFO'],
            ['codigo' => 518, 'nombre' => 'AUTORETEICA BIMESTRAL PUERTO TRIUNFO'],
            ['codigo' => 519, 'nombre' => 'ICA ANUAL SAN LUÍS'],
            ['codigo' => 520, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SAN LUÍS'],
            ['codigo' => 521, 'nombre' => 'EXOGENA MUNICIPAL SAN LUÍS'],
            ['codigo' => 522, 'nombre' => 'ICA ANUAL SANTA ROSA DE OSOS'],
            ['codigo' => 523, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SANTA ROSA DE OSOS'],
            ['codigo' => 524, 'nombre' => 'ICA ANUAL SEGOVIA'],
            ['codigo' => 525, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SEGOVIA'],
            ['codigo' => 526, 'nombre' => 'ICA ANUAL PITALITO'],
            ['codigo' => 527, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL PITALITO'],
            ['codigo' => 528, 'nombre' => 'ICA ANUAL PUERTO BOYACÁ'],
            ['codigo' => 529, 'nombre' => 'RETEICA MENSUAL PUERTO BOYACÁ'],
            ['codigo' => 530, 'nombre' => 'AUTORETEICA BIMESTRAL PUERTO BOYACÁ'],
            ['codigo' => 531, 'nombre' => 'EXOGENA MUNICIPAL PUERTO BOYACÁ'],
            ['codigo' => 532, 'nombre' => 'ICA ANUAL CARTAGO'],
            ['codigo' => 533, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL CARTAGO'],
            ['codigo' => 534, 'nombre' => 'EXOGENA MUNICIPAL CARTAGO'],
            ['codigo' => 535, 'nombre' => 'ICA ANUAL JURADÓ'],
            ['codigo' => 536, 'nombre' => 'ICA ANUAL SAN CAYETANO - NORTE DE SANTANDER'],
            ['codigo' => 537, 'nombre' => 'ICA MENSUAL SAN CAYETANO - NORTE DE SANTANDER'],
            ['codigo' => 538, 'nombre' => 'EXOGENA MUNICIPAL SAN CAYETANO - NORTE DE SANTANDER'],
            ['codigo' => 539, 'nombre' => 'ICA ANUAL SOPETRAN'],
            ['codigo' => 540, 'nombre' => 'RETEICA BIMESTRAL SOPETRAN'],
            ['codigo' => 541, 'nombre' => 'AUTORETEICA BIMESTRAL PUERTO LIBERTADOR'],
            ['codigo' => 542, 'nombre' => 'EXÓGENA MUNICIPAL PUERTO LIBERTADOR'],
            ['codigo' => 543, 'nombre' => 'AUTORETEICA BIMESTRAL SAHAGÚN'],
            ['codigo' => 544, 'nombre' => 'EXÓGENA MUNICIPAL SAHAGÚN'],
            ['codigo' => 545, 'nombre' => 'EXÓGENA MUNICIPAL MALAMBO'],
            ['codigo' => 546, 'nombre' => 'ICA ANUAL MALAMBO'],
            ['codigo' => 547, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL MALAMBO'],
            ['codigo' => 548, 'nombre' => 'EXÓGENA MUNICIPAL TOCANCIPÁ'],
            ['codigo' => 549, 'nombre' => 'ICA ANUAL TOCANCIPÁ'],
            ['codigo' => 550, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL TOCANCIPÁ'],
            ['codigo' => 551, 'nombre' => 'ICA ANUAL SANTAFÉ DE ANTIOQUIA'],
            ['codigo' => 552, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL SANTAFÉ DE ANTIOQUIA'],
            ['codigo' => 553, 'nombre' => 'ICA ANUAL ARBOLETES'],
            ['codigo' => 554, 'nombre' => 'RETEICA BIMESTRAL ARBOLETES'],
            ['codigo' => 555, 'nombre' => 'EXOGENA MUNICIPAL ARBOLETES'],
            ['codigo' => 556, 'nombre' => 'ICA ANUAL CAREPA'],
            ['codigo' => 557, 'nombre' => 'RETEICA BIMESTRAL CAREPA'],
            ['codigo' => 558, 'nombre' => 'AUTORETEICA MENSUAL CAREPA'],
            ['codigo' => 559, 'nombre' => 'EXOGENA MUNICIPAL CAREPA'],
            ['codigo' => 560, 'nombre' => 'ICA ANUAL SAN JUAN DE URABÁ'],
            ['codigo' => 561, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL SAN JUAN DE URABÁ'],
            ['codigo' => 562, 'nombre' => 'EXOGENA MUNICIPAL SAN JUAN DE URABÁ'],
            ['codigo' => 563, 'nombre' => 'ICA ANUAL SAN PEDRO DE URABÁ'],
            ['codigo' => 564, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL SAN PEDRO DE URABÁ'],
            ['codigo' => 565, 'nombre' => 'ICA ANUAL TURBO'],
            ['codigo' => 566, 'nombre' => 'RETEICA BIMESTRAL TURBO'],
            ['codigo' => 567, 'nombre' => 'AUTORETEICA BIMESTRAL TURBO'],
            ['codigo' => 568, 'nombre' => 'ICA ANUAL GUAYABETAL'],
            ['codigo' => 569, 'nombre' => 'RETEICA BIMESTRAL GUAYABETAL'],
            ['codigo' => 570, 'nombre' => 'ICA ANUAL LA PLATA'],
            ['codigo' => 571, 'nombre' => 'RETEICA BIMESTRAL PERSONAS Y EMPRESAS - LA PLATA'],
            ['codigo' => 572, 'nombre' => 'RETEICA BIMESTRAL SECTOR FINANCIERO - LA PLATA'],
            ['codigo' => 573, 'nombre' => 'EXOGENA MUNICIPAL LA PLATA'],
            ['codigo' => 574, 'nombre' => 'ICA ANUAL MONTENEGRO'],
            ['codigo' => 575, 'nombre' => 'EXOGENA MUNICIPAL GRANDES CONTRIBUYENTES - MONTENEGRO'],
            ['codigo' => 576, 'nombre' => 'EXOGENA MUNICIPAL PERSONAS Y EMPRESAS - MONTENEGRO'],
            ['codigo' => 577, 'nombre' => 'RETEICA BIMESTRAL MONTENEGRO'],
            ['codigo' => 578, 'nombre' => 'ICA ANUAL SALENTO'],
            ['codigo' => 579, 'nombre' => 'RETEICA BIMESTRAL SALENTO'],
            ['codigo' => 580, 'nombre' => 'RETEICA BIMESTRAL GRANADA'],
            ['codigo' => 581, 'nombre' => 'ICA ANUAL ENTRERRÍOS'],
            ['codigo' => 582, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL ENTRERRÍOS'],
            ['codigo' => 583, 'nombre' => 'EXOGENA MUNICIPAL ENTRERRÍOS'],
            ['codigo' => 584, 'nombre' => 'ICA ANUAL MACEO'],
            ['codigo' => 585, 'nombre' => 'RETEICA BIMESTRAL MACEO'],
            ['codigo' => 586, 'nombre' => 'EXOGENA MUNICIPAL MACEO'],
            ['codigo' => 587, 'nombre' => 'ICA ANUAL SAN ANTERO'],
            ['codigo' => 588, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL SAN ANTERO'],
            ['codigo' => 589, 'nombre' => 'ICA ANUAL REMEDIOS'],
            ['codigo' => 590, 'nombre' => 'RETEICA BIMESTRAL REMEDIOS'],
            ['codigo' => 591, 'nombre' => 'EXOGENA MUNICIPAL SEGOVIA'],
            ['codigo' => 592, 'nombre' => 'ICA ANUAL SANTO DOMINGO'],
            ['codigo' => 593, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL SANTO DOMINGO'],
            ['codigo' => 594, 'nombre' => 'ICA ANUAL PEQUE'],
            ['codigo' => 595, 'nombre' => 'RETEICA BIMESTRAL PEQUE'],
            ['codigo' => 596, 'nombre' => 'EXOGENA MUNICIPAL PEQUE - GRANDES CONTRIBUYENTES'],
            ['codigo' => 597, 'nombre' => 'EXOGENA MUNICIPAL PEQUE - EMPRESAS Y PERSONAS'],
            ['codigo' => 598, 'nombre' => 'EXOGENA MUNICIPAL PEQUE - ENTIDADES PUBLICAS'],
            ['codigo' => 599, 'nombre' => 'EXOGENA MUNICIPAL PEQUE - GRUPOS ECONÓMICOS Y/O EMPRESARIALES'],
            ['codigo' => 601, 'nombre' => 'RETEICA MENSUAL LA APARTADA'],
            ['codigo' => 602, 'nombre' => 'ICA ANUAL MONTELÍBANO'],
            ['codigo' => 603, 'nombre' => 'ICA BIMESTRAL MONTELÍBANO'],
            ['codigo' => 604, 'nombre' => 'ICA BIMESTRAL  RÉGIMEN PREFERENCIAL MONTELÍBANO'],
            ['codigo' => 605, 'nombre' => 'RETEICA MENSUAL MONTELÍBANO'],
            ['codigo' => 606, 'nombre' => 'EXOGENA MUNICIPAL MONTELÍBANO'],
            ['codigo' => 607, 'nombre' => 'ICA ANUAL SAN MARCOS'],
            ['codigo' => 608, 'nombre' => 'RETEICA Y AUTORETEICA MENSUAL SAN MARCOS'],
            ['codigo' => 609, 'nombre' => 'EXOGENA MUNICIPAL SAN MARCOS'],
            ['codigo' => 610, 'nombre' => 'ICA ANUAL LA APARTADA'],
            ['codigo' => 611, 'nombre' => 'ICA ANUAL RIVERA'],
            ['codigo' => 612, 'nombre' => 'RETEICA BIMESTRAL RIVERA'],
            ['codigo' => 613, 'nombre' => 'EXOGENA MUNICIPAL RIVERA'],
            ['codigo' => 614, 'nombre' => 'RETEICA Y AUTORETEICA BIMESTRAL LETICIA'],
            ['codigo' => 615, 'nombre' => 'ICA ANUAL LETICIA'],
            ['codigo' => 616, 'nombre' => 'EXÓGENA MUNICIPAL GUARNE'],
            ['codigo' => 617, 'nombre' => 'ICA ANUAL CALARCA'],
            ['codigo' => 618, 'nombre' => 'RETEICA BIMESTRAL CALARCA'],
            ['codigo' => 619, 'nombre' => 'EXÓGENA MUNICIPAL CALARCA - GRANDES CONTRIBUYENTES'],
            ['codigo' => 620, 'nombre' => 'EXÓGENA MUNICIPAL CALARCA - PERSONAS Y EMPRESAS'],
            ['codigo' => 621, 'nombre' => 'EXÓGENA MUNICIPAL SOACHA'],
            ['codigo' => 622, 'nombre' => 'EXÓGENA MUNICIPAL CIUDAD BOLÍVAR']
        ];
        ObligacionesMunicipalesDian::insert($impuestos);
    }
}
